-- Script de Seed: Profissionais de Saúde
-- Cria profissionais de saúde para os estabelecimentos do tenant
-- Depende de: Tenant, Estabelecimentos, ConselhosProfissionais, EspecialidadesMedicas
-- Executado quando app.seed.enabled=true

-- Médico Clínico Geral - UBS Centro
INSERT INTO public.profissionais_saude (
    id,
    criado_em,
    atualizado_em,
    tenant_id,
    estabelecimento_id,
    ativo,
    nome_completo,
    cpf,
    data_nascimento,
    sexo,
    estado_civil,
    escolaridade,
    identidade_genero,
    raca_cor,
    tem_deficiencia,
    rg,
    orgao_emissor_rg,
    uf_emissao_rg,
    nacionalidade,
    naturalidade,
    registro_profissional,
    conselho_id,
    uf_registro,
    data_emissao_registro,
    status_registro,
    tipo_profissional,
    cns,
    codigo_cbo,
    descricao_cbo,
    telefone,
    email,
    observacoes
)
SELECT 
    gen_random_uuid(),
    NOW(),
    NOW(),
    t.id,
    e.id,
    true,
    'Dr. João Silva Santos',
    '12345678901',
    '1980-05-15'::date,
    1,
    2,
    7,
    1,
    1,
    false,
    'MG1234567',
    'SSP/MG',
    'MG',
    1,
    'Santa Rita do Sapucaí',
    '12345',
    (SELECT id FROM public.conselhos_profissionais WHERE sigla = 'CRM' LIMIT 1),
    'MG',
    NOW() - INTERVAL '10 years',
    1,
    22,
    '703000000000000',
    '225110',
    'Médico Clínico Geral',
    '3535511001',
    'joao.santos@santaritadosapucai.mg.gov.br',
    'Médico da atenção básica, responsável pelo atendimento na UBS Centro'
FROM public.tenants t, public.estabelecimentos e
WHERE t.slug = 'prefeitura-santa-rita-do-sapucai'
  AND e.codigo_cnes = '7101234'
  AND e.tenant_id = t.id
  AND NOT EXISTS (SELECT 1 FROM public.profissionais_saude ps WHERE ps.cpf = '12345678901' AND ps.tenant_id = t.id);

-- Enfermeira - UBS Centro
INSERT INTO public.profissionais_saude (
    id,
    criado_em,
    atualizado_em,
    tenant_id,
    estabelecimento_id,
    ativo,
    nome_completo,
    cpf,
    data_nascimento,
    sexo,
    estado_civil,
    escolaridade,
    identidade_genero,
    raca_cor,
    tem_deficiencia,
    rg,
    orgao_emissor_rg,
    uf_emissao_rg,
    nacionalidade,
    naturalidade,
    registro_profissional,
    conselho_id,
    uf_registro,
    data_emissao_registro,
    status_registro,
    tipo_profissional,
    cns,
    codigo_cbo,
    descricao_cbo,
    telefone,
    email,
    observacoes
)
SELECT 
    gen_random_uuid(),
    NOW(),
    NOW(),
    t.id,
    e.id,
    true,
    'Enf. Maria Oliveira Costa',
    '23456789012',
    '1985-08-20'::date,
    2,
    2,
    7,
    1,
    3,
    false,
    'MG2345678',
    'SSP/MG',
    'MG',
    1,
    'Pouso Alegre',
    '23456',
    (SELECT id FROM public.conselhos_profissionais WHERE sigla = 'COREN' LIMIT 1),
    'MG',
    NOW() - INTERVAL '8 years',
    1,
    1,
    '703000000000001',
    '223505',
    'Enfermeiro',
    '3535511002',
    'maria.costa@santaritadosapucai.mg.gov.br',
    'Enfermeira da atenção básica, coordenadora de enfermagem da UBS Centro'
FROM public.tenants t, public.estabelecimentos e
WHERE t.slug = 'prefeitura-santa-rita-do-sapucai'
  AND e.codigo_cnes = '7101234'
  AND e.tenant_id = t.id
  AND NOT EXISTS (SELECT 1 FROM public.profissionais_saude ps WHERE ps.cpf = '23456789012' AND ps.tenant_id = t.id);

-- Técnico de Enfermagem - UBS Centro
INSERT INTO public.profissionais_saude (
    id,
    criado_em,
    atualizado_em,
    tenant_id,
    estabelecimento_id,
    ativo,
    nome_completo,
    cpf,
    data_nascimento,
    sexo,
    estado_civil,
    escolaridade,
    identidade_genero,
    raca_cor,
    tem_deficiencia,
    rg,
    orgao_emissor_rg,
    uf_emissao_rg,
    nacionalidade,
    naturalidade,
    registro_profissional,
    conselho_id,
    uf_registro,
    data_emissao_registro,
    status_registro,
    tipo_profissional,
    cns,
    codigo_cbo,
    descricao_cbo,
    telefone,
    email,
    observacoes
)
SELECT 
    gen_random_uuid(),
    NOW(),
    NOW(),
    t.id,
    e.id,
    true,
    'Ana Paula Ferreira',
    '34567890123',
    '1990-03-10'::date,
    2,
    1,
    5,
    1,
    1,
    false,
    'MG3456789',
    'SSP/MG',
    'MG',
    1,
    'Santa Rita do Sapucaí',
    '34567',
    (SELECT id FROM public.conselhos_profissionais WHERE sigla = 'COREN' LIMIT 1),
    'MG',
    NOW() - INTERVAL '5 years',
    1,
    2,
    '703000000000002',
    '322205',
    'Técnico de Enfermagem',
    '3535511003',
    'ana.ferreira@santaritadosapucai.mg.gov.br',
    'Técnica de enfermagem, atua na UBS Centro'
FROM public.tenants t, public.estabelecimentos e
WHERE t.slug = 'prefeitura-santa-rita-do-sapucai'
  AND e.codigo_cnes = '7101234'
  AND e.tenant_id = t.id
  AND NOT EXISTS (SELECT 1 FROM public.profissionais_saude ps WHERE ps.cpf = '34567890123' AND ps.tenant_id = t.id);

-- Médico Pediatra - UBS Centro
INSERT INTO public.profissionais_saude (
    id,
    criado_em,
    atualizado_em,
    tenant_id,
    estabelecimento_id,
    ativo,
    nome_completo,
    cpf,
    data_nascimento,
    sexo,
    estado_civil,
    escolaridade,
    identidade_genero,
    raca_cor,
    tem_deficiencia,
    rg,
    orgao_emissor_rg,
    uf_emissao_rg,
    nacionalidade,
    naturalidade,
    registro_profissional,
    conselho_id,
    uf_registro,
    data_emissao_registro,
    status_registro,
    tipo_profissional,
    cns,
    codigo_cbo,
    descricao_cbo,
    telefone,
    email,
    observacoes
)
SELECT 
    gen_random_uuid(),
    NOW(),
    NOW(),
    t.id,
    e.id,
    true,
    'Dra. Juliana Rodrigues Lima',
    '45678901234',
    '1978-11-25'::date,
    2,
    2,
    7,
    1,
    1,
    false,
    'MG4567890',
    'SSP/MG',
    'MG',
    1,
    'Varginha',
    '45678',
    (SELECT id FROM public.conselhos_profissionais WHERE sigla = 'CRM' LIMIT 1),
    'MG',
    NOW() - INTERVAL '12 years',
    1,
    23,
    '703000000000003',
    '225140',
    'Médico Pediatra',
    '3535511004',
    'juliana.lima@santaritadosapucai.mg.gov.br',
    'Pediatra responsável pelo atendimento infantil na UBS Centro'
FROM public.tenants t, public.estabelecimentos e
WHERE t.slug = 'prefeitura-santa-rita-do-sapucai'
  AND e.codigo_cnes = '7101234'
  AND e.tenant_id = t.id
  AND NOT EXISTS (SELECT 1 FROM public.profissionais_saude ps WHERE ps.cpf = '45678901234' AND ps.tenant_id = t.id);

-- Médico Plantonista - UPA 24 Horas
INSERT INTO public.profissionais_saude (
    id,
    criado_em,
    atualizado_em,
    tenant_id,
    estabelecimento_id,
    ativo,
    nome_completo,
    cpf,
    data_nascimento,
    sexo,
    estado_civil,
    escolaridade,
    identidade_genero,
    raca_cor,
    tem_deficiencia,
    rg,
    orgao_emissor_rg,
    uf_emissao_rg,
    nacionalidade,
    naturalidade,
    registro_profissional,
    conselho_id,
    uf_registro,
    data_emissao_registro,
    status_registro,
    tipo_profissional,
    cns,
    codigo_cbo,
    descricao_cbo,
    telefone,
    email,
    observacoes
)
SELECT 
    gen_random_uuid(),
    NOW(),
    NOW(),
    t.id,
    e.id,
    true,
    'Dr. Carlos Alberto Souza',
    '56789012345',
    '1975-02-18'::date,
    1,
    2,
    7,
    1,
    1,
    false,
    'MG5678901',
    'SSP/MG',
    'MG',
    1,
    'Itajubá',
    '56789',
    (SELECT id FROM public.conselhos_profissionais WHERE sigla = 'CRM' LIMIT 1),
    'MG',
    NOW() - INTERVAL '15 years',
    1,
    29,
    '703000000000004',
    '225195',
    'Médico de Urgência e Emergência',
    '3535512001',
    'carlos.souza@santaritadosapucai.mg.gov.br',
    'Médico plantonista da UPA 24 Horas, especialista em urgência e emergência'
FROM public.tenants t, public.estabelecimentos e
WHERE t.slug = 'prefeitura-santa-rita-do-sapucai'
  AND e.codigo_cnes = '7101235'
  AND e.tenant_id = t.id
  AND NOT EXISTS (SELECT 1 FROM public.profissionais_saude ps WHERE ps.cpf = '56789012345' AND ps.tenant_id = t.id);

-- Enfermeira - UPA 24 Horas
INSERT INTO public.profissionais_saude (
    id,
    criado_em,
    atualizado_em,
    tenant_id,
    estabelecimento_id,
    ativo,
    nome_completo,
    cpf,
    data_nascimento,
    sexo,
    estado_civil,
    escolaridade,
    identidade_genero,
    raca_cor,
    tem_deficiencia,
    rg,
    orgao_emissor_rg,
    uf_emissao_rg,
    nacionalidade,
    naturalidade,
    registro_profissional,
    conselho_id,
    uf_registro,
    data_emissao_registro,
    status_registro,
    tipo_profissional,
    cns,
    codigo_cbo,
    descricao_cbo,
    telefone,
    email,
    observacoes
)
SELECT 
    gen_random_uuid(),
    NOW(),
    NOW(),
    t.id,
    e.id,
    true,
    'Enf. Patricia Almeida',
    '67890123456',
    '1988-06-30'::date,
    2,
    1,
    7,
    1,
    3,
    false,
    'MG6789012',
    'SSP/MG',
    'MG',
    1,
    'Pouso Alegre',
    '67890',
    (SELECT id FROM public.conselhos_profissionais WHERE sigla = 'COREN' LIMIT 1),
    'MG',
    NOW() - INTERVAL '6 years',
    1,
    31,
    '703000000000005',
    '223510',
    'Enfermeiro de Urgência e Emergência',
    '3535512002',
    'patricia.almeida@santaritadosapucai.mg.gov.br',
    'Enfermeira plantonista da UPA 24 Horas'
FROM public.tenants t, public.estabelecimentos e
WHERE t.slug = 'prefeitura-santa-rita-do-sapucai'
  AND e.codigo_cnes = '7101235'
  AND e.tenant_id = t.id
  AND NOT EXISTS (SELECT 1 FROM public.profissionais_saude ps WHERE ps.cpf = '67890123456' AND ps.tenant_id = t.id);

-- Médico Clínico Geral - UBS Novo Horizonte
INSERT INTO public.profissionais_saude (
    id,
    criado_em,
    atualizado_em,
    tenant_id,
    estabelecimento_id,
    ativo,
    nome_completo,
    cpf,
    data_nascimento,
    sexo,
    estado_civil,
    escolaridade,
    identidade_genero,
    raca_cor,
    tem_deficiencia,
    rg,
    orgao_emissor_rg,
    uf_emissao_rg,
    nacionalidade,
    naturalidade,
    registro_profissional,
    conselho_id,
    uf_registro,
    data_emissao_registro,
    status_registro,
    tipo_profissional,
    cns,
    codigo_cbo,
    descricao_cbo,
    telefone,
    email,
    observacoes
)
SELECT 
    gen_random_uuid(),
    NOW(),
    NOW(),
    t.id,
    e.id,
    true,
    'Dr. Roberto Mendes Pereira',
    '78901234567',
    '1982-09-12'::date,
    1,
    2,
    7,
    1,
    1,
    false,
    'MG7890123',
    'SSP/MG',
    'MG',
    1,
    'Santa Rita do Sapucaí',
    '78901',
    (SELECT id FROM public.conselhos_profissionais WHERE sigla = 'CRM' LIMIT 1),
    'MG',
    NOW() - INTERVAL '9 years',
    1,
    22,
    '703000000000006',
    '225110',
    'Médico Clínico Geral',
    '3535515001',
    'roberto.pereira@santaritadosapucai.mg.gov.br',
    'Médico da UBS Novo Horizonte'
FROM public.tenants t, public.estabelecimentos e
WHERE t.slug = 'prefeitura-santa-rita-do-sapucai'
  AND e.codigo_cnes = '7101238'
  AND e.tenant_id = t.id
  AND NOT EXISTS (SELECT 1 FROM public.profissionais_saude ps WHERE ps.cpf = '78901234567' AND ps.tenant_id = t.id);

