package com.upsaude.dto.estabelecimento;

import java.time.LocalTime;
import java.time.OffsetDateTime;
import java.util.UUID;
import lombok.*;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ConfiguracaoEstabelecimentoDTO {
    private UUID id;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
    private Boolean active;
    private EstabelecimentosDTO estabelecimento;
    private Integer duracaoPadraoAtendimentoMinutos;
    private Integer intervaloMinimoEntreAtendimentosMinutos;
    private Boolean permiteAgendamentoOnline;
    private Integer antecendenciaMaximaAgendamentoDias;
    private Integer antecendenciaMinimaAgendamentoHoras;
    private Boolean permiteReagendamento;
    private Integer prazoReagendamentoHoras;
    private Boolean permiteCancelamentoOnline;
    private Integer prazoCancelamentoHoras;
    private Boolean permiteEncaixe;
    private Integer maximoEncaixesPorDia;
    private Boolean permiteFilaEspera;
    private Integer tamanhoMaximoFilaEspera;
    private Boolean permitePriorizacao;
    private Boolean verificaConflitoHorario;
    private Boolean permiteSobreposicaoAtendimentos;
    private LocalTime horarioFuncionamentoInicio;
    private LocalTime horarioFuncionamentoFim;
    private LocalTime horarioAlmocoInicio;
    private LocalTime horarioAlmocoFim;
    private Boolean funcionaSabado;
    private LocalTime horarioSabadoInicio;
    private LocalTime horarioSabadoFim;
    private Boolean funcionaDomingo;
    private LocalTime horarioDomingoInicio;
    private LocalTime horarioDomingoFim;
    private Boolean funcionaFeriados;
    private Boolean enviaNotificacaoEmail;
    private Boolean enviaNotificacaoSms;
    private Boolean enviaNotificacaoWhatsapp;
    private Boolean enviaLembrete24h;
    private Boolean enviaLembrete1h;
    private Boolean enviaConfirmacaoAgendamento;
    private Boolean enviaNotificacaoCancelamento;
    private Boolean enviaNotificacaoReagendamento;
    private Boolean enviaNotificacaoResultadoExame;
    private Boolean enviaAvisoFalta;
    private Integer tempoEsperaAvisoFaltaMinutos;
    private Boolean enviaNotificacaoFilaEspera;
    private String servidorSmtp;
    private Integer portaSmtp;
    private String emailRemetente;
    private String nomeRemetente;
    private String usuarioSmtp;
    private String senhaSmtp;
    private Boolean sslSmtp;
    private Boolean tlsSmtp;
    private String provedorSms;
    private String apiKeySms;
    private String apiSecretSms;
    private String telefoneRemetenteSms;
    private String provedorWhatsapp;
    private String apiKeyWhatsapp;
    private String apiSecretWhatsapp;
    private String telefoneRemetenteWhatsapp;
    private String webhookUrlWhatsapp;
    private Boolean permiteCheckinOnline;
    private Integer tempoAntecipacaoCheckinMinutos;
    private Boolean registraPresencaAutomatica;
    private Integer tempoToleranciaAtrasoMinutos;
    private Boolean cancelaAutomaticoAposAtraso;
    private Integer tempoCancelamentoAutomaticoMinutos;
    private Boolean registraAuditoriaCompleta;
    private Integer retencaoDadosMeses;
    private Boolean exigeJustificativaCancelamento;
    private Boolean exigeJustificativaReagendamento;
    private Boolean permiteAcessoPacientePortal;
    private Boolean permiteAgendamentoProfissional;
    private Boolean permiteCancelamentoProfissional;
    private Boolean geraRelatorioProdutividade;
    private Boolean geraRelatorioNaoComparecimento;
    private Boolean geraRelatorioEstatisticas;
    private Boolean mantemHistoricoCompleto;
    private Boolean compartilhaHistoricoEntreEstabelecimentos;
    private Boolean permiteVisualizacaoHistoricoPaciente;
    private Boolean isolamentoDadosEstabelecimento;
    private Boolean compartilhaRecursosTenant;
    private String timezone;
    private String idioma;
    private String formatoData;
    private String formatoHora;
    private String configuracaoJson;
    private String observacoes;
}
