-- Script de Seed: Estabelecimentos de Saúde
-- Cria 6 estabelecimentos filhos do Tenant de Santa Rita do Sapucaí
-- Executado quando app.seed.enabled=true

-- Nota: Este script assume que o tenant já foi criado no script 01-tenant.sql
-- O tenant_id será obtido via subquery

-- 1. UBS Centro
INSERT INTO public.estabelecimentos (
    id,
    criado_em,
    atualizado_em,
    tenant_id,
    ativo,
    nome,
    nome_fantasia,
    tipo,
    codigo_cnes,
    cnpj,
    natureza_juridica,
    registro_oficial,
    telefone,
    telefone_secundario,
    email,
    site,
    status_funcionamento,
    data_abertura,
    quantidade_leitos,
    quantidade_consultorios,
    quantidade_salas_cirurgia,
    quantidade_ambulatorios,
    area_construida_metros_quadrados,
    area_total_metros_quadrados,
    latitude,
    longitude,
    observacoes
) 
SELECT 
    gen_random_uuid(),
    NOW(),
    NOW(),
    t.id,
    true,
    'UBS Centro - Santa Rita do Sapucaí',
    'UBS Centro',
    'UBS',
    '7101234',
    '12345678000101',
    'ADMINISTRACAO_PUBLICA_DIRETA',
    '12345',
    '3535512001',
    '3535512002',
    'ubs.centro@santaritadosapucai.mg.gov.br',
    NULL,
    'EM_FUNCIONAMENTO',
    NOW() - INTERVAL '10 years',
    0,
    8,
    0,
    2,
    450.00,
    800.00,
    -22.2511,
    -45.7056,
    'Unidade Básica de Saúde localizada no centro da cidade'
FROM public.tenants t
WHERE t.slug = 'prefeitura-santa-rita-do-sapucai'
ON CONFLICT DO NOTHING;

-- 2. UPA 24h
INSERT INTO public.estabelecimentos (
    id,
    criado_em,
    atualizado_em,
    tenant_id,
    ativo,
    nome,
    nome_fantasia,
    tipo,
    codigo_cnes,
    cnpj,
    natureza_juridica,
    registro_oficial,
    telefone,
    telefone_secundario,
    email,
    site,
    status_funcionamento,
    data_abertura,
    quantidade_leitos,
    quantidade_consultorios,
    quantidade_salas_cirurgia,
    quantidade_ambulatorios,
    area_construida_metros_quadrados,
    area_total_metros_quadrados,
    latitude,
    longitude,
    observacoes
) 
SELECT 
    gen_random_uuid(),
    NOW(),
    NOW(),
    t.id,
    true,
    'UPA 24 Horas - Santa Rita do Sapucaí',
    'UPA 24h',
    'UPA',
    '7101235',
    '12345678000102',
    'ADMINISTRACAO_PUBLICA_DIRETA',
    '12346',
    '3535512100',
    '3535512101',
    'upa24h@santaritadosapucai.mg.gov.br',
    NULL,
    'EM_FUNCIONAMENTO',
    NOW() - INTERVAL '5 years',
    30,
    12,
    2,
    4,
    1200.00,
    2500.00,
    -22.2600,
    -45.7100,
    'Unidade de Pronto Atendimento funcionando 24 horas'
FROM public.tenants t
WHERE t.slug = 'prefeitura-santa-rita-do-sapucai'
ON CONFLICT DO NOTHING;

-- 3. Posto de Saúde - Bairro São Cristóvão
INSERT INTO public.estabelecimentos (
    id,
    criado_em,
    atualizado_em,
    tenant_id,
    ativo,
    nome,
    nome_fantasia,
    tipo,
    codigo_cnes,
    cnpj,
    natureza_juridica,
    registro_oficial,
    telefone,
    telefone_secundario,
    email,
    site,
    status_funcionamento,
    data_abertura,
    quantidade_leitos,
    quantidade_consultorios,
    quantidade_salas_cirurgia,
    quantidade_ambulatorios,
    area_construida_metros_quadrados,
    area_total_metros_quadrados,
    latitude,
    longitude,
    observacoes
) 
SELECT 
    gen_random_uuid(),
    NOW(),
    NOW(),
    t.id,
    true,
    'Posto de Saúde São Cristóvão',
    'PS São Cristóvão',
    'POSTO_SAUDE',
    '7101236',
    '12345678000103',
    'ADMINISTRACAO_PUBLICA_DIRETA',
    '12347',
    '3535512200',
    NULL,
    'ps.saocristovao@santaritadosapucai.mg.gov.br',
    NULL,
    'EM_FUNCIONAMENTO',
    NOW() - INTERVAL '8 years',
    0,
    4,
    0,
    1,
    280.00,
    500.00,
    -22.2400,
    -45.7000,
    'Posto de Saúde no Bairro São Cristóvão'
FROM public.tenants t
WHERE t.slug = 'prefeitura-santa-rita-do-sapucai'
ON CONFLICT DO NOTHING;

-- 4. Hospital Municipal
INSERT INTO public.estabelecimentos (
    id,
    criado_em,
    atualizado_em,
    tenant_id,
    ativo,
    nome,
    nome_fantasia,
    tipo,
    codigo_cnes,
    cnpj,
    natureza_juridica,
    registro_oficial,
    telefone,
    telefone_secundario,
    email,
    site,
    status_funcionamento,
    data_abertura,
    quantidade_leitos,
    quantidade_consultorios,
    quantidade_salas_cirurgia,
    quantidade_ambulatorios,
    area_construida_metros_quadrados,
    area_total_metros_quadrados,
    latitude,
    longitude,
    observacoes
) 
SELECT 
    gen_random_uuid(),
    NOW(),
    NOW(),
    t.id,
    true,
    'Hospital Municipal de Santa Rita do Sapucaí',
    'Hospital Municipal',
    'HOSPITAL',
    '7101237',
    '12345678000104',
    'ADMINISTRACAO_PUBLICA_DIRETA',
    '12348',
    '3535513000',
    '3535513001',
    'hospital@santaritadosapucai.mg.gov.br',
    'https://www.hospital-srs.mg.gov.br',
    'EM_FUNCIONAMENTO',
    NOW() - INTERVAL '15 years',
    80,
    25,
    4,
    8,
    3500.00,
    6000.00,
    -22.2550,
    -45.7080,
    'Hospital Municipal com atendimento geral e especialidades'
FROM public.tenants t
WHERE t.slug = 'prefeitura-santa-rita-do-sapucai'
ON CONFLICT DO NOTHING;

-- 5. UBS Bairro Novo Horizonte
INSERT INTO public.estabelecimentos (
    id,
    criado_em,
    atualizado_em,
    tenant_id,
    ativo,
    nome,
    nome_fantasia,
    tipo,
    codigo_cnes,
    cnpj,
    natureza_juridica,
    registro_oficial,
    telefone,
    telefone_secundario,
    email,
    site,
    status_funcionamento,
    data_abertura,
    quantidade_leitos,
    quantidade_consultorios,
    quantidade_salas_cirurgia,
    quantidade_ambulatorios,
    area_construida_metros_quadrados,
    area_total_metros_quadrados,
    latitude,
    longitude,
    observacoes
) 
SELECT 
    gen_random_uuid(),
    NOW(),
    NOW(),
    t.id,
    true,
    'UBS Novo Horizonte',
    'UBS Novo Horizonte',
    'UBS',
    '7101238',
    '12345678000105',
    'ADMINISTRACAO_PUBLICA_DIRETA',
    '12349',
    '3535512400',
    NULL,
    'ubs.novohorizonte@santaritadosapucai.mg.gov.br',
    NULL,
    'EM_FUNCIONAMENTO',
    NOW() - INTERVAL '6 years',
    0,
    6,
    0,
    2,
    380.00,
    650.00,
    -22.2300,
    -45.6950,
    'Unidade Básica de Saúde no Bairro Novo Horizonte'
FROM public.tenants t
WHERE t.slug = 'prefeitura-santa-rita-do-sapucai'
ON CONFLICT DO NOTHING;

-- 6. UBS Bairro Jardim Primavera
INSERT INTO public.estabelecimentos (
    id,
    criado_em,
    atualizado_em,
    tenant_id,
    ativo,
    nome,
    nome_fantasia,
    tipo,
    codigo_cnes,
    cnpj,
    natureza_juridica,
    registro_oficial,
    telefone,
    telefone_secundario,
    email,
    site,
    status_funcionamento,
    data_abertura,
    quantidade_leitos,
    quantidade_consultorios,
    quantidade_salas_cirurgia,
    quantidade_ambulatorios,
    area_construida_metros_quadrados,
    area_total_metros_quadrados,
    latitude,
    longitude,
    observacoes
) 
SELECT 
    gen_random_uuid(),
    NOW(),
    NOW(),
    t.id,
    true,
    'UBS Jardim Primavera',
    'UBS Jardim Primavera',
    'UBS',
    '7101239',
    '12345678000106',
    'ADMINISTRACAO_PUBLICA_DIRETA',
    '12350',
    '3535512500',
    NULL,
    'ubs.jardimprimavera@santaritadosapucai.mg.gov.br',
    NULL,
    'EM_FUNCIONAMENTO',
    NOW() - INTERVAL '7 years',
    0,
    5,
    0,
    2,
    320.00,
    580.00,
    -22.2650,
    -45.7150,
    'Unidade Básica de Saúde no Bairro Jardim Primavera'
FROM public.tenants t
WHERE t.slug = 'prefeitura-santa-rita-do-sapucai'
ON CONFLICT DO NOTHING;

