-- Script de Seed: Pacientes
-- Cria pacientes para os estabelecimentos do tenant
-- Depende de: Tenant, Estabelecimentos, Enderecos
-- Executado quando app.seed.enabled=true

-- Paciente 1 - Adulto
INSERT INTO public.pacientes (
    id,
    criado_em,
    atualizado_em,
    tenant_id,
    estabelecimento_id,
    ativo,
    nome_completo,
    cpf,
    rg,
    cns,
    data_nascimento,
    sexo,
    estado_civil,
    telefone,
    email,
    nome_mae,
    nome_pai,
    raca_cor,
    nacionalidade,
    naturalidade,
    municipio_nascimento_ibge,
    escolaridade,
    ocupacao_profissao,
    situacao_rua,
    status_paciente,
    cartao_sus_ativo,
    cns_validado,
    tipo_cns,
    acompanhado_por_equipe_esf,
    observacoes
)
SELECT 
    gen_random_uuid(),
    NOW(),
    NOW(),
    t.id,
    e.id,
    true,
    'José da Silva',
    '11122233344',
    'MG1112223',
    '703000012345678',
    '1975-03-15'::date,
    1,
    2,
    '3535511001',
    'jose.silva@email.com',
    'Maria da Silva',
    'João da Silva',
    1,
    1,
    'Santa Rita do Sapucaí',
    '3543204',
    5,
    'Pedreiro',
    false,
    1,
    true,
    true,
    1,
    false,
    'Paciente da UBS Centro'
FROM public.tenants t, public.estabelecimentos e
WHERE t.slug = 'prefeitura-santa-rita-do-sapucai'
  AND e.codigo_cnes = '7101234'
  AND e.tenant_id = t.id
  AND NOT EXISTS (SELECT 1 FROM public.pacientes p WHERE p.cpf = '11122233344' AND p.tenant_id = t.id);

-- Paciente 2 - Criança
INSERT INTO public.pacientes (
    id,
    criado_em,
    atualizado_em,
    tenant_id,
    estabelecimento_id,
    ativo,
    nome_completo,
    cpf,
    rg,
    cns,
    data_nascimento,
    sexo,
    estado_civil,
    telefone,
    email,
    nome_mae,
    nome_pai,
    responsavel_nome,
    responsavel_cpf,
    responsavel_telefone,
    raca_cor,
    nacionalidade,
    naturalidade,
    municipio_nascimento_ibge,
    escolaridade,
    situacao_rua,
    status_paciente,
    cartao_sus_ativo,
    cns_validado,
    tipo_cns,
    acompanhado_por_equipe_esf,
    observacoes
)
SELECT 
    gen_random_uuid(),
    NOW(),
    NOW(),
    t.id,
    e.id,
    true,
    'Ana Clara Santos',
    '22233344455',
    NULL,
    '703000012345679',
    '2018-06-20'::date,
    2,
    1,
    '3535511002',
    NULL,
    'Patricia Santos',
    'Carlos Santos',
    'Patricia Santos',
    '44455566677',
    '3535511002',
    1,
    1,
    'Santa Rita do Sapucaí',
    '3543204',
    1,
    false,
    1,
    true,
    true,
    1,
    true,
    'Criança acompanhada pela equipe ESF'
FROM public.tenants t, public.estabelecimentos e
WHERE t.slug = 'prefeitura-santa-rita-do-sapucai'
  AND e.codigo_cnes = '7101234'
  AND e.tenant_id = t.id
  AND NOT EXISTS (SELECT 1 FROM public.pacientes p WHERE p.cpf = '22233344455' AND p.tenant_id = t.id);

-- Paciente 3 - Idoso
INSERT INTO public.pacientes (
    id,
    criado_em,
    atualizado_em,
    tenant_id,
    estabelecimento_id,
    ativo,
    nome_completo,
    cpf,
    rg,
    cns,
    data_nascimento,
    sexo,
    estado_civil,
    telefone,
    email,
    nome_mae,
    nome_pai,
    raca_cor,
    nacionalidade,
    naturalidade,
    municipio_nascimento_ibge,
    escolaridade,
    ocupacao_profissao,
    situacao_rua,
    status_paciente,
    cartao_sus_ativo,
    cns_validado,
    tipo_cns,
    acompanhado_por_equipe_esf,
    observacoes
)
SELECT 
    gen_random_uuid(),
    NOW(),
    NOW(),
    t.id,
    e.id,
    true,
    'Maria Oliveira Costa',
    '33344455566',
    'MG3334445',
    '703000012345680',
    '1940-11-08'::date,
    2,
    4,
    '3535511003',
    NULL,
    'Joana Oliveira',
    'Pedro Oliveira',
    1,
    1,
    'Pouso Alegre',
    '3538006',
    2,
    'Aposentada',
    false,
    1,
    true,
    true,
    1,
    true,
    'Paciente idosa, acompanhada pela equipe ESF'
FROM public.tenants t, public.estabelecimentos e
WHERE t.slug = 'prefeitura-santa-rita-do-sapucai'
  AND e.codigo_cnes = '7101234'
  AND e.tenant_id = t.id
  AND NOT EXISTS (SELECT 1 FROM public.pacientes p WHERE p.cpf = '33344455566' AND p.tenant_id = t.id);

-- Paciente 4 - UPA
INSERT INTO public.pacientes (
    id,
    criado_em,
    atualizado_em,
    tenant_id,
    estabelecimento_id,
    ativo,
    nome_completo,
    cpf,
    rg,
    cns,
    data_nascimento,
    sexo,
    estado_civil,
    telefone,
    email,
    nome_mae,
    nome_pai,
    raca_cor,
    nacionalidade,
    naturalidade,
    municipio_nascimento_ibge,
    escolaridade,
    ocupacao_profissao,
    situacao_rua,
    status_paciente,
    cartao_sus_ativo,
    cns_validado,
    tipo_cns,
    acompanhado_por_equipe_esf,
    observacoes
)
SELECT 
    gen_random_uuid(),
    NOW(),
    NOW(),
    t.id,
    e.id,
    true,
    'Roberto Mendes',
    '44455566677',
    'MG4445556',
    '703000012345681',
    '1988-02-25'::date,
    1,
    1,
    '3535512001',
    'roberto.mendes@email.com',
    'Lucia Mendes',
    'Paulo Mendes',
    3,
    1,
    'Santa Rita do Sapucaí',
    '3543204',
    5,
    'Motorista',
    false,
    1,
    true,
    true,
    1,
    false,
    'Paciente atendido na UPA'
FROM public.tenants t, public.estabelecimentos e
WHERE t.slug = 'prefeitura-santa-rita-do-sapucai'
  AND e.codigo_cnes = '7101235'
  AND e.tenant_id = t.id
  AND NOT EXISTS (SELECT 1 FROM public.pacientes p WHERE p.cpf = '44455566677' AND p.tenant_id = t.id);

-- Paciente 5 - UBS Novo Horizonte
INSERT INTO public.pacientes (
    id,
    criado_em,
    atualizado_em,
    tenant_id,
    estabelecimento_id,
    ativo,
    nome_completo,
    cpf,
    rg,
    cns,
    data_nascimento,
    sexo,
    estado_civil,
    telefone,
    email,
    nome_mae,
    nome_pai,
    raca_cor,
    nacionalidade,
    naturalidade,
    municipio_nascimento_ibge,
    escolaridade,
    ocupacao_profissao,
    situacao_rua,
    status_paciente,
    cartao_sus_ativo,
    cns_validado,
    tipo_cns,
    acompanhado_por_equipe_esf,
    observacoes
)
SELECT 
    gen_random_uuid(),
    NOW(),
    NOW(),
    t.id,
    e.id,
    true,
    'Fernanda Rodrigues',
    '55566677788',
    'MG5556667',
    '703000012345682',
    '1992-09-10'::date,
    2,
    2,
    '3535515001',
    'fernanda.rodrigues@email.com',
    'Sandra Rodrigues',
    'Marcos Rodrigues',
    1,
    1,
    'Santa Rita do Sapucaí',
    '3543204',
    7,
    'Professora',
    false,
    1,
    true,
    true,
    1,
    true,
    'Paciente da UBS Novo Horizonte'
FROM public.tenants t, public.estabelecimentos e
WHERE t.slug = 'prefeitura-santa-rita-do-sapucai'
  AND e.codigo_cnes = '7101238'
  AND e.tenant_id = t.id
  AND NOT EXISTS (SELECT 1 FROM public.pacientes p WHERE p.cpf = '55566677788' AND p.tenant_id = t.id);

