
package com.upsaude.integration.cnes.wsdl.equipe;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "EquipeServicePortType", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/equipeservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EquipeServicePortType {


    /**
     * 
     * 				Consultar os equipes do
     * 				Estabelecimento de Saude pelo código do CNES.
     * 			
     * 
     * @param requestPesquisarEquipe
     * @return
     *     returns com.upsaude.integration.cnes.wsdl.equipe.ResponsePesquisarEquipe
     * @throws EquipeFault
     */
    @WebMethod
    @WebResult(name = "responsePesquisarEquipe", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/equipeservice", partName = "responsePesquisarEquipe")
    public ResponsePesquisarEquipe pesquisarEquipe(
        @WebParam(name = "requestPesquisarEquipe", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/equipeservice", partName = "requestPesquisarEquipe")
        RequestPesquisarEquipe requestPesquisarEquipe)
        throws EquipeFault
    ;

    /**
     * 
     * 				Consultar o detalhe de um equipe para um Código de Identificação Nacional da Equipe.
     * 			
     * 
     * @param requestDetalharEquipe
     * @return
     *     returns com.upsaude.integration.cnes.wsdl.equipe.ResponseDetalharEquipe
     * @throws EquipeFault
     */
    @WebMethod
    @WebResult(name = "responseDetalharEquipe", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/equipeservice", partName = "responseDetalharEquipe")
    public ResponseDetalharEquipe detalharEquipe(
        @WebParam(name = "requestDetalharEquipe", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/equipeservice", partName = "requestDetalharEquipe")
        RequestDetalharEquipe requestDetalharEquipe)
        throws EquipeFault
    ;

}
