
package com.upsaude.integration.cnes.wsdl.equipe;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "EquipeService", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/equipeservice", wsdlLocation = "file:/Users/wagnergrilo/Desktop/WGB/sistemas/UPSaude/code_antigravity/UPSaude-final-back/src/main/resources/assets/wsdl/cnes/v1r0/EquipeService_v1r0.wsdl")
public class EquipeService
    extends Service
{

    private static final URL EQUIPESERVICE_WSDL_LOCATION;
    private static final WebServiceException EQUIPESERVICE_EXCEPTION;
    private static final QName EQUIPESERVICE_QNAME = new QName("http://servicos.saude.gov.br/cnes/v1r0/equipeservice", "EquipeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/wagnergrilo/Desktop/WGB/sistemas/UPSaude/code_antigravity/UPSaude-final-back/src/main/resources/assets/wsdl/cnes/v1r0/EquipeService_v1r0.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EQUIPESERVICE_WSDL_LOCATION = url;
        EQUIPESERVICE_EXCEPTION = e;
    }

    public EquipeService() {
        super(__getWsdlLocation(), EQUIPESERVICE_QNAME);
    }

    public EquipeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EQUIPESERVICE_QNAME, features);
    }

    public EquipeService(URL wsdlLocation) {
        super(wsdlLocation, EQUIPESERVICE_QNAME);
    }

    public EquipeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EQUIPESERVICE_QNAME, features);
    }

    public EquipeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EquipeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EquipeServicePortType
     */
    @WebEndpoint(name = "EquipeServicePort")
    public EquipeServicePortType getEquipeServicePort() {
        return super.getPort(new QName("http://servicos.saude.gov.br/cnes/v1r0/equipeservice", "EquipeServicePort"), EquipeServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EquipeServicePortType
     */
    @WebEndpoint(name = "EquipeServicePort")
    public EquipeServicePortType getEquipeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicos.saude.gov.br/cnes/v1r0/equipeservice", "EquipeServicePort"), EquipeServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns EquipeServicePortType
     */
    @WebEndpoint(name = "EquipeServiceSOAP11Port")
    public EquipeServicePortType getEquipeServiceSOAP11Port() {
        return super.getPort(new QName("http://servicos.saude.gov.br/cnes/v1r0/equipeservice", "EquipeServiceSOAP11Port"), EquipeServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EquipeServicePortType
     */
    @WebEndpoint(name = "EquipeServiceSOAP11Port")
    public EquipeServicePortType getEquipeServiceSOAP11Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicos.saude.gov.br/cnes/v1r0/equipeservice", "EquipeServiceSOAP11Port"), EquipeServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EQUIPESERVICE_EXCEPTION!= null) {
            throw EQUIPESERVICE_EXCEPTION;
        }
        return EQUIPESERVICE_WSDL_LOCATION;
    }

}
