
package com.upsaude.integration.cnes.wsdl.leito;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "LeitoService", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/leitoservice", wsdlLocation = "file:/Users/wagnergrilo/Desktop/WGB/sistemas/UPSaude/code_antigravity/UPSaude-final-back/src/main/resources/assets/wsdl/cnes/v1r0/LeitoService_v1r0.wsdl")
public class LeitoService
    extends Service
{

    private static final URL LEITOSERVICE_WSDL_LOCATION;
    private static final WebServiceException LEITOSERVICE_EXCEPTION;
    private static final QName LEITOSERVICE_QNAME = new QName("http://servicos.saude.gov.br/cnes/v1r0/leitoservice", "LeitoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/wagnergrilo/Desktop/WGB/sistemas/UPSaude/code_antigravity/UPSaude-final-back/src/main/resources/assets/wsdl/cnes/v1r0/LeitoService_v1r0.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LEITOSERVICE_WSDL_LOCATION = url;
        LEITOSERVICE_EXCEPTION = e;
    }

    public LeitoService() {
        super(__getWsdlLocation(), LEITOSERVICE_QNAME);
    }

    public LeitoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LEITOSERVICE_QNAME, features);
    }

    public LeitoService(URL wsdlLocation) {
        super(wsdlLocation, LEITOSERVICE_QNAME);
    }

    public LeitoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LEITOSERVICE_QNAME, features);
    }

    public LeitoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LeitoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LeitoServicePortType
     */
    @WebEndpoint(name = "LeitoServicePort")
    public LeitoServicePortType getLeitoServicePort() {
        return super.getPort(new QName("http://servicos.saude.gov.br/cnes/v1r0/leitoservice", "LeitoServicePort"), LeitoServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LeitoServicePortType
     */
    @WebEndpoint(name = "LeitoServicePort")
    public LeitoServicePortType getLeitoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicos.saude.gov.br/cnes/v1r0/leitoservice", "LeitoServicePort"), LeitoServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LEITOSERVICE_EXCEPTION!= null) {
            throw LEITOSERVICE_EXCEPTION;
        }
        return LEITOSERVICE_WSDL_LOCATION;
    }

}
