
package com.upsaude.integration.cnes.wsdl.leito;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "LeitoServicePortType", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/leitoservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LeitoServicePortType {


    /**
     * Consultar os leitos do
     * 				Estabelecimento de Saude pelo código do CNES.
     * 
     * @param requestConsultarLeitosCNES
     * @return
     *     returns com.upsaude.integration.cnes.wsdl.leito.ResponseConsultarLeitosCNES
     * @throws LeitoFault
     */
    @WebMethod
    @WebResult(name = "responseConsultarLeitosCNES", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/leitoservice", partName = "responseConsultarLeitosCNES")
    public ResponseConsultarLeitosCNES consultarLeitosCNES(
        @WebParam(name = "requestConsultarLeitosCNES", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/leitoservice", partName = "requestConsultarLeitosCNES")
        RequestConsultarLeitosCNES requestConsultarLeitosCNES)
        throws LeitoFault
    ;

}
