#!/usr/bin/env python3
"""
Script para gerar SQL de inserção de códigos CID-10 (Classificação Internacional de Doenças).
Gera códigos CID-10 reais e comuns utilizados no Brasil.
"""

# Dados dos códigos CID-10 mais comuns e importantes
# Formato: (codigo, descricao, descricao_abreviada, categoria, subcategoria, sexo_restricao, idade_minima, idade_maxima)
CID_DOENCAS = [
    # Capítulo I - Doenças Infecciosas e Parasitárias (A00-B99)
    ('A00', 'Cólera', 'Cólera', 'Doenças Infecciosas', 'Cólera', None, None, None),
    ('A01', 'Febres tifóide e paratifóide', 'Febre tifóide', 'Doenças Infecciosas', 'Febres Tifóides', None, None, None),
    ('A02', 'Outras infecções devidas a Salmonella', 'Salmonelose', 'Doenças Infecciosas', 'Salmonelose', None, None, None),
    ('A03', 'Shiguelose', 'Shiguelose', 'Doenças Infecciosas', 'Shiguelose', None, None, None),
    ('A04', 'Outras infecções intestinais bacterianas', 'Infecção intestinal bacteriana', 'Doenças Infecciosas', 'Infecções Intestinais', None, None, None),
    ('A05', 'Outras intoxicações alimentares bacterianas', 'Intoxicação alimentar bacteriana', 'Doenças Infecciosas', 'Intoxicações Alimentares', None, None, None),
    ('A06', 'Amebíase', 'Amebíase', 'Doenças Infecciosas', 'Amebíase', None, None, None),
    ('A07', 'Outras doenças intestinais por protozoários', 'Doença intestinal por protozoário', 'Doenças Infecciosas', 'Protozoários', None, None, None),
    ('A08', 'Infecções intestinais virais', 'Infecção intestinal viral', 'Doenças Infecciosas', 'Infecções Virais', None, None, None),
    ('A09', 'Gastroenterite e colite de origem infecciosa e não especificada', 'Gastroenterite infecciosa', 'Doenças Infecciosas', 'Gastroenterite', None, None, None),
    ('A15', 'Tuberculose respiratória, com confirmação bacteriológica e histológica', 'Tuberculose respiratória confirmada', 'Doenças Infecciosas', 'Tuberculose', None, None, None),
    ('A15.0', 'Tuberculose pulmonar, com confirmação por exame bacteriológico com cultura', 'Tuberculose pulmonar confirmada', 'Doenças Infecciosas', 'Tuberculose', None, None, None),
    ('A15.1', 'Tuberculose pulmonar, com confirmação apenas por exame microscópico do escarro', 'Tuberculose pulmonar microscópica', 'Doenças Infecciosas', 'Tuberculose', None, None, None),
    ('A16', 'Tuberculose respiratória, sem confirmação bacteriológica ou histológica', 'Tuberculose respiratória não confirmada', 'Doenças Infecciosas', 'Tuberculose', None, None, None),
    ('A17', 'Tuberculose do sistema nervoso', 'Tuberculose do SNC', 'Doenças Infecciosas', 'Tuberculose', None, None, None),
    ('A18', 'Tuberculose de outros órgãos', 'Tuberculose de outros órgãos', 'Doenças Infecciosas', 'Tuberculose', None, None, None),
    ('A19', 'Tuberculose miliar', 'Tuberculose miliar', 'Doenças Infecciosas', 'Tuberculose', None, None, None),
    ('A20', 'Peste', 'Peste', 'Doenças Infecciosas', 'Peste', None, None, None),
    ('A21', 'Tularemia', 'Tularemia', 'Doenças Infecciosas', 'Tularemia', None, None, None),
    ('A22', 'Carbúnculo', 'Carbúnculo', 'Doenças Infecciosas', 'Carbúnculo', None, None, None),
    ('A23', 'Brucelose', 'Brucelose', 'Doenças Infecciosas', 'Brucelose', None, None, None),
    ('A24', 'Mormo e melioidose', 'Mormo', 'Doenças Infecciosas', 'Mormo', None, None, None),
    ('A25', 'Febre por mordedura de rato', 'Febre por mordedura de rato', 'Doenças Infecciosas', 'Febre por Mordedura', None, None, None),
    ('A26', 'Erisipeloide', 'Erisipeloide', 'Doenças Infecciosas', 'Erisipeloide', None, None, None),
    ('A27', 'Leptospirose', 'Leptospirose', 'Doenças Infecciosas', 'Leptospirose', None, None, None),
    ('A28', 'Outras doenças bacterianas zoonóticas não classificadas em outra parte', 'Doença bacteriana zoonótica', 'Doenças Infecciosas', 'Zoonoses', None, None, None),
    ('A30', 'Hanseníase [lepra]', 'Hanseníase', 'Doenças Infecciosas', 'Hanseníase', None, None, None),
    ('A31', 'Infecções devidas a outras micobactérias', 'Infecção por micobactéria', 'Doenças Infecciosas', 'Micobactérias', None, None, None),
    ('A32', 'Listeriose', 'Listeriose', 'Doenças Infecciosas', 'Listeriose', None, None, None),
    ('A33', 'Tétano do recém-nascido', 'Tétano neonatal', 'Doenças Infecciosas', 'Tétano', None, None, 28),
    ('A34', 'Tétano obstétrico', 'Tétano obstétrico', 'Doenças Infecciosas', 'Tétano', 'F', None, None),
    ('A35', 'Outros tipos de tétano', 'Tétano', 'Doenças Infecciosas', 'Tétano', None, None, None),
    ('A36', 'Difteria', 'Difteria', 'Doenças Infecciosas', 'Difteria', None, None, None),
    ('A37', 'Coqueluche', 'Coqueluche', 'Doenças Infecciosas', 'Coqueluche', None, None, None),
    ('A38', 'Escarlatina', 'Escarlatina', 'Doenças Infecciosas', 'Escarlatina', None, None, None),
    ('A39', 'Doença meningocócica', 'Doença meningocócica', 'Doenças Infecciosas', 'Meningocócica', None, None, None),
    ('A40', 'Septicemia estreptocócica', 'Septicemia estreptocócica', 'Doenças Infecciosas', 'Septicemia', None, None, None),
    ('A41', 'Outras septicemias', 'Septicemia', 'Doenças Infecciosas', 'Septicemia', None, None, None),
    ('A42', 'Actinomicose', 'Actinomicose', 'Doenças Infecciosas', 'Actinomicose', None, None, None),
    ('A43', 'Nocardiose', 'Nocardiose', 'Doenças Infecciosas', 'Nocardiose', None, None, None),
    ('A44', 'Bartonelose', 'Bartonelose', 'Doenças Infecciosas', 'Bartonelose', None, None, None),
    ('A46', 'Erisipela', 'Erisipela', 'Doenças Infecciosas', 'Erisipela', None, None, None),
    ('A48', 'Outras doenças bacterianas não classificadas em outra parte', 'Doença bacteriana', 'Doenças Infecciosas', 'Bacterianas', None, None, None),
    ('A49', 'Infecção bacteriana de localização não especificada', 'Infecção bacteriana', 'Doenças Infecciosas', 'Bacterianas', None, None, None),
    ('A50', 'Sífilis congênita', 'Sífilis congênita', 'Doenças Infecciosas', 'Sífilis', None, None, None),
    ('A51', 'Sífilis precoce', 'Sífilis precoce', 'Doenças Infecciosas', 'Sífilis', None, None, None),
    ('A52', 'Sífilis tardia', 'Sífilis tardia', 'Doenças Infecciosas', 'Sífilis', None, None, None),
    ('A53', 'Outras formas e formas não especificadas de sífilis', 'Sífilis', 'Doenças Infecciosas', 'Sífilis', None, None, None),
    ('A54', 'Infecção gonocócica', 'Gonorreia', 'Doenças Infecciosas', 'Gonorreia', None, None, None),
    ('A55', 'Linfogranuloma (venéreo) por clamídia', 'Linfogranuloma venéreo', 'Doenças Infecciosas', 'Clamídia', None, None, None),
    ('A56', 'Outras infecções causadas por clamídias transmitidas por via sexual', 'Infecção por clamídia', 'Doenças Infecciosas', 'Clamídia', None, None, None),
    ('A57', 'Cancro mole', 'Cancro mole', 'Doenças Infecciosas', 'Cancro Mole', None, None, None),
    ('A58', 'Granuloma inguinal', 'Granuloma inguinal', 'Doenças Infecciosas', 'Granuloma Inguinal', None, None, None),
    ('A59', 'Tricomoníase', 'Tricomoníase', 'Doenças Infecciosas', 'Tricomoníase', None, None, None),
    ('A60', 'Infecção anogenital por vírus do herpes [herpes simples]', 'Herpes genital', 'Doenças Infecciosas', 'Herpes', None, None, None),
    ('A63', 'Outras doenças de transmissão predominantemente sexual, não classificadas em outra parte', 'DST', 'Doenças Infecciosas', 'DST', None, None, None),
    ('A64', 'Doenças sexualmente transmitidas não especificadas', 'DST não especificada', 'Doenças Infecciosas', 'DST', None, None, None),
    ('A65', 'Bouba não venérea', 'Bouba', 'Doenças Infecciosas', 'Bouba', None, None, None),
    ('A66', 'Frambésia', 'Frambésia', 'Doenças Infecciosas', 'Frambésia', None, None, None),
    ('A67', 'Pinta [carate]', 'Pinta', 'Doenças Infecciosas', 'Pinta', None, None, None),
    ('A68', 'Febres recorrentes [borrelioses]', 'Febre recorrente', 'Doenças Infecciosas', 'Febre Recorrente', None, None, None),
    ('A69', 'Outras infecções por espiroquetas', 'Infecção por espiroqueta', 'Doenças Infecciosas', 'Espiroquetas', None, None, None),
    ('A70', 'Infecções causadas por Chlamydia psittaci', 'Psitacose', 'Doenças Infecciosas', 'Psitacose', None, None, None),
    ('A71', 'Tracoma', 'Tracoma', 'Doenças Infecciosas', 'Tracoma', None, None, None),
    ('A74', 'Doenças causadas por Chlamydia trachomatis', 'Infecção por Chlamydia trachomatis', 'Doenças Infecciosas', 'Chlamydia', None, None, None),
    ('A75', 'Tifo exantemático', 'Tifo exantemático', 'Doenças Infecciosas', 'Tifo', None, None, None),
    ('A77', 'Febre maculosa [rickettsioses transmitidas por carrapatos]', 'Febre maculosa', 'Doenças Infecciosas', 'Rickettsioses', None, None, None),
    ('A78', 'Febre Q', 'Febre Q', 'Doenças Infecciosas', 'Rickettsioses', None, None, None),
    ('A79', 'Outras rickettsioses', 'Rickettsiose', 'Doenças Infecciosas', 'Rickettsioses', None, None, None),
    ('A80', 'Poliomielite aguda', 'Poliomielite', 'Doenças Infecciosas', 'Poliomielite', None, None, None),
    ('A81', 'Infecções por vírus atípicos do sistema nervoso central', 'Infecção viral do SNC', 'Doenças Infecciosas', 'Virais', None, None, None),
    ('A82', 'Raiva', 'Raiva', 'Doenças Infecciosas', 'Raiva', None, None, None),
    ('A83', 'Encefalite viral transmitida por mosquitos', 'Encefalite viral por mosquito', 'Doenças Infecciosas', 'Encefalite', None, None, None),
    ('A84', 'Encefalite viral transmitida por carrapatos', 'Encefalite viral por carrapato', 'Doenças Infecciosas', 'Encefalite', None, None, None),
    ('A85', 'Outras encefalites virais não classificadas em outra parte', 'Encefalite viral', 'Doenças Infecciosas', 'Encefalite', None, None, None),
    ('A86', 'Encefalite viral não especificada', 'Encefalite viral', 'Doenças Infecciosas', 'Encefalite', None, None, None),
    ('A87', 'Meningite viral', 'Meningite viral', 'Doenças Infecciosas', 'Meningite', None, None, None),
    ('A88', 'Outras infecções virais do sistema nervoso central não classificadas em outra parte', 'Infecção viral do SNC', 'Doenças Infecciosas', 'Virais', None, None, None),
    ('A89', 'Infecção viral não especificada do sistema nervoso central', 'Infecção viral do SNC', 'Doenças Infecciosas', 'Virais', None, None, None),
    ('A90', 'Dengue [dengue clássico]', 'Dengue', 'Doenças Infecciosas', 'Dengue', None, None, None),
    ('A91', 'Febre hemorrágica devida ao vírus do dengue', 'Dengue hemorrágico', 'Doenças Infecciosas', 'Dengue', None, None, None),
    ('A92', 'Outras febres virais transmitidas por mosquitos', 'Febre viral por mosquito', 'Doenças Infecciosas', 'Virais', None, None, None),
    ('A93', 'Outras febres por vírus transmitidas por artrópodes não classificadas em outra parte', 'Febre viral por artrópode', 'Doenças Infecciosas', 'Virais', None, None, None),
    ('A94', 'Febre viral transmitida por artrópodes não especificada', 'Febre viral', 'Doenças Infecciosas', 'Virais', None, None, None),
    ('A95', 'Febre amarela', 'Febre amarela', 'Doenças Infecciosas', 'Febre Amarela', None, None, None),
    ('A96', 'Febre hemorrágica por arenavírus', 'Febre hemorrágica', 'Doenças Infecciosas', 'Febre Hemorrágica', None, None, None),
    ('A98', 'Outras febres hemorrágicas por vírus não classificadas em outra parte', 'Febre hemorrágica viral', 'Doenças Infecciosas', 'Febre Hemorrágica', None, None, None),
    ('A99', 'Febres hemorrágicas virais não especificadas', 'Febre hemorrágica viral', 'Doenças Infecciosas', 'Febre Hemorrágica', None, None, None),
    ('B00', 'Infecções pelo vírus do herpes [herpes simples]', 'Herpes simples', 'Doenças Infecciosas', 'Herpes', None, None, None),
    ('B01', 'Varicela [catapora]', 'Varicela', 'Doenças Infecciosas', 'Varicela', None, None, None),
    ('B02', 'Herpes zoster [zona]', 'Herpes zoster', 'Doenças Infecciosas', 'Herpes', None, None, None),
    ('B03', 'Varíola', 'Varíola', 'Doenças Infecciosas', 'Varíola', None, None, None),
    ('B04', 'Varíola dos macacos', 'Varíola dos macacos', 'Doenças Infecciosas', 'Varíola', None, None, None),
    ('B05', 'Sarampo', 'Sarampo', 'Doenças Infecciosas', 'Sarampo', None, None, None),
    ('B06', 'Rubéola', 'Rubéola', 'Doenças Infecciosas', 'Rubéola', None, None, None),
    ('B07', 'Verrugas virais', 'Verrugas virais', 'Doenças Infecciosas', 'Verrugas', None, None, None),
    ('B08', 'Outras infecções virais caracterizadas por lesões da pele e das membranas mucosas, não classificadas em outra parte', 'Infecção viral de pele', 'Doenças Infecciosas', 'Virais', None, None, None),
    ('B09', 'Infecção viral não especificada caracterizada por lesões da pele e das membranas mucosas', 'Infecção viral de pele', 'Doenças Infecciosas', 'Virais', None, None, None),
    ('B15', 'Hepatite A aguda', 'Hepatite A', 'Doenças Infecciosas', 'Hepatite', None, None, None),
    ('B16', 'Hepatite B aguda', 'Hepatite B', 'Doenças Infecciosas', 'Hepatite', None, None, None),
    ('B17', 'Outras hepatites virais agudas', 'Hepatite viral aguda', 'Doenças Infecciosas', 'Hepatite', None, None, None),
    ('B18', 'Hepatite viral crônica', 'Hepatite viral crônica', 'Doenças Infecciosas', 'Hepatite', None, None, None),
    ('B19', 'Hepatite viral não especificada', 'Hepatite viral', 'Doenças Infecciosas', 'Hepatite', None, None, None),
    ('B20', 'Doença pelo vírus da imunodeficiência humana [HIV], resultando em doenças infecciosas e parasitárias', 'HIV com infecções', 'Doenças Infecciosas', 'HIV', None, None, None),
    ('B21', 'Doença pelo vírus da imunodeficiência humana [HIV], resultando em neoplasias malignas', 'HIV com neoplasias', 'Doenças Infecciosas', 'HIV', None, None, None),
    ('B22', 'Doença pelo vírus da imunodeficiência humana [HIV], resultando em outras doenças especificadas', 'HIV com outras doenças', 'Doenças Infecciosas', 'HIV', None, None, None),
    ('B23', 'Doença pelo vírus da imunodeficiência humana [HIV], resultando em outras afecções', 'HIV com afecções', 'Doenças Infecciosas', 'HIV', None, None, None),
    ('B24', 'Doença pelo vírus da imunodeficiência humana [HIV], não especificada', 'HIV', 'Doenças Infecciosas', 'HIV', None, None, None),
    ('B25', 'Doença pelo citomegalovírus', 'Citomegalovírus', 'Doenças Infecciosas', 'Citomegalovírus', None, None, None),
    ('B26', 'Caxumba [parotidite epidêmica]', 'Caxumba', 'Doenças Infecciosas', 'Caxumba', None, None, None),
    ('B27', 'Mononucleose infecciosa', 'Mononucleose', 'Doenças Infecciosas', 'Mononucleose', None, None, None),
    ('B30', 'Ceratoconjuntivite viral', 'Ceratoconjuntivite viral', 'Doenças Infecciosas', 'Conjuntivite', None, None, None),
    ('B33', 'Outras doenças por vírus não classificadas em outra parte', 'Doença viral', 'Doenças Infecciosas', 'Virais', None, None, None),
    ('B34', 'Infecção viral de localização não especificada', 'Infecção viral', 'Doenças Infecciosas', 'Virais', None, None, None),
    ('B35', 'Dermatofitose', 'Dermatofitose', 'Doenças Infecciosas', 'Micoses', None, None, None),
    ('B36', 'Outras micoses superficiais', 'Micose superficial', 'Doenças Infecciosas', 'Micoses', None, None, None),
    ('B37', 'Candidíase', 'Candidíase', 'Doenças Infecciosas', 'Micoses', None, None, None),
    ('B38', 'Coccidioidomicose', 'Coccidioidomicose', 'Doenças Infecciosas', 'Micoses', None, None, None),
    ('B39', 'Histoplasmose', 'Histoplasmose', 'Doenças Infecciosas', 'Micoses', None, None, None),
    ('B40', 'Blastomicose', 'Blastomicose', 'Doenças Infecciosas', 'Micoses', None, None, None),
    ('B41', 'Paracoccidioidomicose', 'Paracoccidioidomicose', 'Doenças Infecciosas', 'Micoses', None, None, None),
    ('B42', 'Esporotricose', 'Esporotricose', 'Doenças Infecciosas', 'Micoses', None, None, None),
    ('B43', 'Cromomicose e abscesso feomicótico', 'Cromomicose', 'Doenças Infecciosas', 'Micoses', None, None, None),
    ('B44', 'Aspergilose', 'Aspergilose', 'Doenças Infecciosas', 'Micoses', None, None, None),
    ('B45', 'Criptococose', 'Criptococose', 'Doenças Infecciosas', 'Micoses', None, None, None),
    ('B46', 'Zigomicose', 'Zigomicose', 'Doenças Infecciosas', 'Micoses', None, None, None),
    ('B47', 'Micetoma', 'Micetoma', 'Doenças Infecciosas', 'Micoses', None, None, None),
    ('B48', 'Outras micoses não classificadas em outra parte', 'Micose', 'Doenças Infecciosas', 'Micoses', None, None, None),
    ('B49', 'Micose não especificada', 'Micose', 'Doenças Infecciosas', 'Micoses', None, None, None),
    ('B50', 'Malária por Plasmodium falciparum', 'Malária por P. falciparum', 'Doenças Infecciosas', 'Malária', None, None, None),
    ('B51', 'Malária por Plasmodium vivax', 'Malária por P. vivax', 'Doenças Infecciosas', 'Malária', None, None, None),
    ('B52', 'Malária por Plasmodium malariae', 'Malária por P. malariae', 'Doenças Infecciosas', 'Malária', None, None, None),
    ('B53', 'Outras formas de malária confirmadas por parasitologia', 'Malária', 'Doenças Infecciosas', 'Malária', None, None, None),
    ('B54', 'Malária não especificada', 'Malária', 'Doenças Infecciosas', 'Malária', None, None, None),
    ('B55', 'Leishmaniose', 'Leishmaniose', 'Doenças Infecciosas', 'Leishmaniose', None, None, None),
    ('B56', 'Tripanossomíase africana', 'Tripanossomíase africana', 'Doenças Infecciosas', 'Tripanossomíase', None, None, None),
    ('B57', 'Doença de Chagas', 'Doença de Chagas', 'Doenças Infecciosas', 'Doença de Chagas', None, None, None),
    ('B58', 'Toxoplasmose', 'Toxoplasmose', 'Doenças Infecciosas', 'Toxoplasmose', None, None, None),
    ('B59', 'Pneumocistose', 'Pneumocistose', 'Doenças Infecciosas', 'Pneumocistose', None, None, None),
    ('B60', 'Outras doenças devidas a protozoários não classificadas em outra parte', 'Doença por protozoário', 'Doenças Infecciosas', 'Protozoários', None, None, None),
    ('B64', 'Doença por protozoários não especificada', 'Doença por protozoário', 'Doenças Infecciosas', 'Protozoários', None, None, None),
    ('B65', 'Esquistossomose [bilharziose]', 'Esquistossomose', 'Doenças Infecciosas', 'Esquistossomose', None, None, None),
    ('B66', 'Outras infecções por trematódeos', 'Infecção por trematódeo', 'Doenças Infecciosas', 'Trematódeos', None, None, None),
    ('B67', 'Equinococose', 'Equinococose', 'Doenças Infecciosas', 'Equinococose', None, None, None),
    ('B68', 'Taeniose', 'Taeniose', 'Doenças Infecciosas', 'Taeniose', None, None, None),
    ('B69', 'Cisticercose', 'Cisticercose', 'Doenças Infecciosas', 'Cisticercose', None, None, None),
    ('B70', 'Difilobotríase e esparganose', 'Difilobotríase', 'Doenças Infecciosas', 'Cestódeos', None, None, None),
    ('B71', 'Outras infecções por cestódeos', 'Infecção por cestódeo', 'Doenças Infecciosas', 'Cestódeos', None, None, None),
    ('B72', 'Dracontíase', 'Dracontíase', 'Doenças Infecciosas', 'Dracontíase', None, None, None),
    ('B73', 'Oncocercose', 'Oncocercose', 'Doenças Infecciosas', 'Oncocercose', None, None, None),
    ('B74', 'Filariose', 'Filariose', 'Doenças Infecciosas', 'Filariose', None, None, None),
    ('B75', 'Triquinelose', 'Triquinelose', 'Doenças Infecciosas', 'Triquinelose', None, None, None),
    ('B76', 'Ancilostomíase', 'Ancilostomíase', 'Doenças Infecciosas', 'Ancilostomíase', None, None, None),
    ('B77', 'Ascaridíase', 'Ascaridíase', 'Doenças Infecciosas', 'Ascaridíase', None, None, None),
    ('B78', 'Estrongiloidíase', 'Estrongiloidíase', 'Doenças Infecciosas', 'Estrongiloidíase', None, None, None),
    ('B79', 'Tricuríase', 'Tricuríase', 'Doenças Infecciosas', 'Tricuríase', None, None, None),
    ('B80', 'Enterobíase', 'Enterobíase', 'Doenças Infecciosas', 'Enterobíase', None, None, None),
    ('B81', 'Outras helmintíases intestinais não classificadas em outra parte', 'Helmintíase intestinal', 'Doenças Infecciosas', 'Helmintíases', None, None, None),
    ('B82', 'Parasitose intestinal não especificada', 'Parasitose intestinal', 'Doenças Infecciosas', 'Parasitoses', None, None, None),
    ('B83', 'Outras helmintíases', 'Helmintíase', 'Doenças Infecciosas', 'Helmintíases', None, None, None),
    ('B85', 'Pediculose e ftiríase', 'Pediculose', 'Doenças Infecciosas', 'Pediculose', None, None, None),
    ('B86', 'Sarna [escabiose]', 'Sarna', 'Doenças Infecciosas', 'Sarna', None, None, None),
    ('B87', 'Miíase', 'Miíase', 'Doenças Infecciosas', 'Miíase', None, None, None),
    ('B88', 'Outras infestações', 'Infestação', 'Doenças Infecciosas', 'Infestações', None, None, None),
    ('B89', 'Doença parasitária não especificada', 'Doença parasitária', 'Doenças Infecciosas', 'Parasitárias', None, None, None),
    ('B90', 'Seqüelas de tuberculose', 'Seqüelas de tuberculose', 'Doenças Infecciosas', 'Seqüelas', None, None, None),
    ('B91', 'Seqüelas de poliomielite', 'Seqüelas de poliomielite', 'Doenças Infecciosas', 'Seqüelas', None, None, None),
    ('B92', 'Seqüelas de hanseníase [lepra]', 'Seqüelas de hanseníase', 'Doenças Infecciosas', 'Seqüelas', None, None, None),
    ('B94', 'Seqüelas de outras doenças infecciosas e parasitárias e das não especificadas', 'Seqüelas de doenças infecciosas', 'Doenças Infecciosas', 'Seqüelas', None, None, None),
    ('B95', 'Estreptococos e estafilococos como causa de doenças classificadas em outros capítulos', 'Infecção por estreptococo/estafilococo', 'Doenças Infecciosas', 'Bacterianas', None, None, None),
    ('B96', 'Outros agentes bacterianos como causa de doenças classificadas em outros capítulos', 'Infecção bacteriana', 'Doenças Infecciosas', 'Bacterianas', None, None, None),
    ('B97', 'Agentes virais como causa de doenças classificadas em outros capítulos', 'Infecção viral', 'Doenças Infecciosas', 'Virais', None, None, None),
    ('B99', 'Outras doenças infecciosas e parasitárias', 'Doença infecciosa', 'Doenças Infecciosas', 'Infecciosas', None, None, None),

    # Capítulo II - Neoplasias [Tumores] (C00-D48)
    ('C00', 'Neoplasia maligna do lábio', 'Câncer de lábio', 'Neoplasias', 'Câncer de Lábio', None, None, None),
    ('C01', 'Neoplasia maligna da base da língua', 'Câncer de base da língua', 'Neoplasias', 'Câncer de Língua', None, None, None),
    ('C02', 'Neoplasia maligna de outras partes e de partes não especificadas da língua', 'Câncer de língua', 'Neoplasias', 'Câncer de Língua', None, None, None),
    ('C03', 'Neoplasia maligna da gengiva', 'Câncer de gengiva', 'Neoplasias', 'Câncer de Boca', None, None, None),
    ('C04', 'Neoplasia maligna do assoalho da boca', 'Câncer de assoalho da boca', 'Neoplasias', 'Câncer de Boca', None, None, None),
    ('C05', 'Neoplasia maligna do palato', 'Câncer de palato', 'Neoplasias', 'Câncer de Boca', None, None, None),
    ('C06', 'Neoplasia maligna de outras partes e de partes não especificadas da boca', 'Câncer de boca', 'Neoplasias', 'Câncer de Boca', None, None, None),
    ('C07', 'Neoplasia maligna da glândula parótida', 'Câncer de parótida', 'Neoplasias', 'Câncer de Glândulas Salivares', None, None, None),
    ('C08', 'Neoplasia maligna de outras glândulas salivares maiores e das não especificadas', 'Câncer de glândula salivar', 'Neoplasias', 'Câncer de Glândulas Salivares', None, None, None),
    ('C09', 'Neoplasia maligna da amígdala', 'Câncer de amígdala', 'Neoplasias', 'Câncer de Amígdala', None, None, None),
    ('C10', 'Neoplasia maligna da orofaringe', 'Câncer de orofaringe', 'Neoplasias', 'Câncer de Faringe', None, None, None),
    ('C11', 'Neoplasia maligna da nasofaringe', 'Câncer de nasofaringe', 'Neoplasias', 'Câncer de Faringe', None, None, None),
    ('C12', 'Neoplasia maligna do seio piriforme', 'Câncer de seio piriforme', 'Neoplasias', 'Câncer de Faringe', None, None, None),
    ('C13', 'Neoplasia maligna da hipofaringe', 'Câncer de hipofaringe', 'Neoplasias', 'Câncer de Faringe', None, None, None),
    ('C14', 'Neoplasia maligna de outras localizações e de localizações mal definidas do lábio, cavidade oral e faringe', 'Câncer de boca/faringe', 'Neoplasias', 'Câncer de Boca', None, None, None),
    ('C15', 'Neoplasia maligna do esôfago', 'Câncer de esôfago', 'Neoplasias', 'Câncer de Esôfago', None, None, None),
    ('C16', 'Neoplasia maligna do estômago', 'Câncer de estômago', 'Neoplasias', 'Câncer de Estômago', None, None, None),
    ('C17', 'Neoplasia maligna do intestino delgado', 'Câncer de intestino delgado', 'Neoplasias', 'Câncer de Intestino', None, None, None),
    ('C18', 'Neoplasia maligna do cólon', 'Câncer de cólon', 'Neoplasias', 'Câncer de Intestino', None, None, None),
    ('C19', 'Neoplasia maligna da junção retossigmoide', 'Câncer de junção retossigmoide', 'Neoplasias', 'Câncer de Intestino', None, None, None),
    ('C20', 'Neoplasia maligna do reto', 'Câncer de reto', 'Neoplasias', 'Câncer de Intestino', None, None, None),
    ('C21', 'Neoplasia maligna do ânus e do canal anal', 'Câncer de ânus', 'Neoplasias', 'Câncer de Intestino', None, None, None),
    ('C22', 'Neoplasia maligna do fígado e das vias biliares intra-hepáticas', 'Câncer de fígado', 'Neoplasias', 'Câncer de Fígado', None, None, None),
    ('C23', 'Neoplasia maligna da vesícula biliar', 'Câncer de vesícula biliar', 'Neoplasias', 'Câncer de Vesícula Biliar', None, None, None),
    ('C24', 'Neoplasia maligna de outras partes e de partes não especificadas das vias biliares', 'Câncer de vias biliares', 'Neoplasias', 'Câncer de Vias Biliares', None, None, None),
    ('C25', 'Neoplasia maligna do pâncreas', 'Câncer de pâncreas', 'Neoplasias', 'Câncer de Pâncreas', None, None, None),
    ('C26', 'Neoplasia maligna de outras localizações e de localizações mal definidas do aparelho digestivo', 'Câncer de aparelho digestivo', 'Neoplasias', 'Câncer de Aparelho Digestivo', None, None, None),
    ('C30', 'Neoplasia maligna da cavidade nasal e dos seios paranasais', 'Câncer de cavidade nasal', 'Neoplasias', 'Câncer de Nariz', None, None, None),
    ('C31', 'Neoplasia maligna da laringe', 'Câncer de laringe', 'Neoplasias', 'Câncer de Laringe', None, None, None),
    ('C32', 'Neoplasia maligna da traqueia', 'Câncer de traqueia', 'Neoplasias', 'Câncer de Traqueia', None, None, None),
    ('C33', 'Neoplasia maligna dos brônquios e dos pulmões', 'Câncer de pulmão', 'Neoplasias', 'Câncer de Pulmão', None, None, None),
    ('C34', 'Neoplasia maligna dos brônquios e dos pulmões', 'Câncer de pulmão', 'Neoplasias', 'Câncer de Pulmão', None, None, None),
    ('C37', 'Neoplasia maligna do timo', 'Câncer de timo', 'Neoplasias', 'Câncer de Timo', None, None, None),
    ('C38', 'Neoplasia maligna do coração, mediastino e pleura', 'Câncer de coração/mediastino', 'Neoplasias', 'Câncer de Coração', None, None, None),
    ('C39', 'Neoplasia maligna de outras localizações e de localizações mal definidas do aparelho respiratório e dos órgãos intratorácicos', 'Câncer de aparelho respiratório', 'Neoplasias', 'Câncer de Aparelho Respiratório', None, None, None),
    ('C40', 'Neoplasia maligna dos ossos e cartilagens articulares dos membros', 'Câncer de osso', 'Neoplasias', 'Câncer de Osso', None, None, None),
    ('C41', 'Neoplasia maligna dos ossos e cartilagens articulares de outras localizações e de localizações não especificadas', 'Câncer de osso', 'Neoplasias', 'Câncer de Osso', None, None, None),
    ('C43', 'Melanoma maligno da pele', 'Melanoma', 'Neoplasias', 'Câncer de Pele', None, None, None),
    ('C44', 'Outras neoplasias malignas da pele', 'Câncer de pele', 'Neoplasias', 'Câncer de Pele', None, None, None),
    ('C45', 'Mesotelioma', 'Mesotelioma', 'Neoplasias', 'Mesotelioma', None, None, None),
    ('C46', 'Sarcoma de Kaposi', 'Sarcoma de Kaposi', 'Neoplasias', 'Sarcoma de Kaposi', None, None, None),
    ('C47', 'Neoplasia maligna dos nervos periféricos e do sistema nervoso autônomo', 'Câncer de nervo periférico', 'Neoplasias', 'Câncer de Nervo', None, None, None),
    ('C48', 'Neoplasia maligna do peritônio e do retroperitônio', 'Câncer de peritônio', 'Neoplasias', 'Câncer de Peritônio', None, None, None),
    ('C49', 'Neoplasia maligna de outros tecidos conjuntivos e dos tecidos moles', 'Câncer de tecido mole', 'Neoplasias', 'Câncer de Tecido Mole', None, None, None),
    ('C50', 'Neoplasia maligna da mama', 'Câncer de mama', 'Neoplasias', 'Câncer de Mama', 'F', None, None),
    ('C51', 'Neoplasia maligna da vulva', 'Câncer de vulva', 'Neoplasias', 'Câncer de Vulva', 'F', None, None),
    ('C52', 'Neoplasia maligna da vagina', 'Câncer de vagina', 'Neoplasias', 'Câncer de Vagina', 'F', None, None),
    ('C53', 'Neoplasia maligna do colo do útero', 'Câncer de colo do útero', 'Neoplasias', 'Câncer de Colo do Útero', 'F', None, None),
    ('C54', 'Neoplasia maligna do corpo do útero', 'Câncer de corpo do útero', 'Neoplasias', 'Câncer de Útero', 'F', None, None),
    ('C55', 'Neoplasia maligna do útero, porção não especificada', 'Câncer de útero', 'Neoplasias', 'Câncer de Útero', 'F', None, None),
    ('C56', 'Neoplasia maligna do ovário', 'Câncer de ovário', 'Neoplasias', 'Câncer de Ovário', 'F', None, None),
    ('C57', 'Neoplasia maligna de outros órgãos genitais femininos e dos não especificados', 'Câncer de órgão genital feminino', 'Neoplasias', 'Câncer de Órgão Genital Feminino', 'F', None, None),
    ('C58', 'Neoplasia maligna da placenta', 'Câncer de placenta', 'Neoplasias', 'Câncer de Placenta', 'F', None, None),
    ('C60', 'Neoplasia maligna do pênis', 'Câncer de pênis', 'Neoplasias', 'Câncer de Pênis', 'M', None, None),
    ('C61', 'Neoplasia maligna da próstata', 'Câncer de próstata', 'Neoplasias', 'Câncer de Próstata', 'M', None, None),
    ('C62', 'Neoplasia maligna do testículo', 'Câncer de testículo', 'Neoplasias', 'Câncer de Testículo', 'M', None, None),
    ('C63', 'Neoplasia maligna de outros órgãos genitais masculinos e dos não especificados', 'Câncer de órgão genital masculino', 'Neoplasias', 'Câncer de Órgão Genital Masculino', 'M', None, None),
    ('C64', 'Neoplasia maligna do rim, exceto pelve renal', 'Câncer de rim', 'Neoplasias', 'Câncer de Rim', None, None, None),
    ('C65', 'Neoplasia maligna da pelve renal', 'Câncer de pelve renal', 'Neoplasias', 'Câncer de Rim', None, None, None),
    ('C66', 'Neoplasia maligna do ureter', 'Câncer de ureter', 'Neoplasias', 'Câncer de Ureter', None, None, None),
    ('C67', 'Neoplasia maligna da bexiga', 'Câncer de bexiga', 'Neoplasias', 'Câncer de Bexiga', None, None, None),
    ('C68', 'Neoplasia maligna de outros órgãos urinários e dos não especificados', 'Câncer de órgão urinário', 'Neoplasias', 'Câncer de Órgão Urinário', None, None, None),
    ('C69', 'Neoplasia maligna do olho e anexos', 'Câncer de olho', 'Neoplasias', 'Câncer de Olho', None, None, None),
    ('C70', 'Neoplasia maligna das meninges', 'Câncer de meninge', 'Neoplasias', 'Câncer de Meninge', None, None, None),
    ('C71', 'Neoplasia maligna do encéfalo', 'Câncer de encéfalo', 'Neoplasias', 'Câncer de Encéfalo', None, None, None),
    ('C72', 'Neoplasia maligna da medula espinhal, dos nervos cranianos e de outras partes do sistema nervoso central', 'Câncer de SNC', 'Neoplasias', 'Câncer de SNC', None, None, None),
    ('C73', 'Neoplasia maligna da glândula tireóide', 'Câncer de tireóide', 'Neoplasias', 'Câncer de Tireóide', None, None, None),
    ('C74', 'Neoplasia maligna da glândula supra-renal', 'Câncer de supra-renal', 'Neoplasias', 'Câncer de Supra-renal', None, None, None),
    ('C75', 'Neoplasia maligna de outras glândulas endócrinas e de estruturas relacionadas', 'Câncer de glândula endócrina', 'Neoplasias', 'Câncer de Glândula Endócrina', None, None, None),
    ('C76', 'Neoplasia maligna de outras localizações e de localizações mal definidas', 'Câncer de localização não especificada', 'Neoplasias', 'Câncer', None, None, None),
    ('C77', 'Neoplasia maligna secundária e não especificada de linfonodos', 'Metástase em linfonodo', 'Neoplasias', 'Metástase', None, None, None),
    ('C78', 'Neoplasia maligna secundária de órgãos respiratórios e digestivos', 'Metástase em órgão respiratório/digestivo', 'Neoplasias', 'Metástase', None, None, None),
    ('C79', 'Neoplasia maligna secundária de outras localizações', 'Metástase', 'Neoplasias', 'Metástase', None, None, None),
    ('C80', 'Neoplasia maligna sem especificação de localização', 'Câncer não especificado', 'Neoplasias', 'Câncer', None, None, None),
    ('C81', 'Doença de Hodgkin', 'Doença de Hodgkin', 'Neoplasias', 'Linfoma', None, None, None),
    ('C82', 'Linfoma não-Hodgkin folicular [nodular]', 'Linfoma não-Hodgkin folicular', 'Neoplasias', 'Linfoma', None, None, None),
    ('C83', 'Linfoma não-Hodgkin difuso', 'Linfoma não-Hodgkin difuso', 'Neoplasias', 'Linfoma', None, None, None),
    ('C84', 'Linfoma de células T periférico e cutâneo', 'Linfoma de células T', 'Neoplasias', 'Linfoma', None, None, None),
    ('C85', 'Outros linfomas não-Hodgkin e os não especificados', 'Linfoma não-Hodgkin', 'Neoplasias', 'Linfoma', None, None, None),
    ('C88', 'Doenças imunoproliferativas malignas', 'Doença imunoproliferativa', 'Neoplasias', 'Doença Imunoproliferativa', None, None, None),
    ('C90', 'Mieloma múltiplo e neoplasias malignas de plasmócitos', 'Mieloma múltiplo', 'Neoplasias', 'Mieloma', None, None, None),
    ('C91', 'Leucemia linfoide', 'Leucemia linfoide', 'Neoplasias', 'Leucemia', None, None, None),
    ('C92', 'Leucemia mieloide', 'Leucemia mieloide', 'Neoplasias', 'Leucemia', None, None, None),
    ('C93', 'Leucemia monocítica', 'Leucemia monocítica', 'Neoplasias', 'Leucemia', None, None, None),
    ('C94', 'Outras leucemias de tipo celular especificado', 'Leucemia', 'Neoplasias', 'Leucemia', None, None, None),
    ('C95', 'Leucemia de tipo celular não especificado', 'Leucemia', 'Neoplasias', 'Leucemia', None, None, None),
    ('C96', 'Outras neoplasias malignas e as não especificadas dos tecidos linfático, hematopoético e tecidos correlatos', 'Neoplasia maligna hematológica', 'Neoplasias', 'Neoplasia Hematológica', None, None, None),
    ('C97', 'Neoplasias malignas de localizações múltiplas independentes (primárias)', 'Neoplasia múltipla', 'Neoplasias', 'Neoplasia Múltipla', None, None, None),
    ('D00', 'Carcinoma in situ da cavidade oral, esôfago e estômago', 'Carcinoma in situ', 'Neoplasias', 'Carcinoma in situ', None, None, None),
    ('D01', 'Carcinoma in situ de outros órgãos digestivos e dos não especificados', 'Carcinoma in situ digestivo', 'Neoplasias', 'Carcinoma in situ', None, None, None),
    ('D02', 'Carcinoma in situ do ouvido médio e do aparelho respiratório', 'Carcinoma in situ respiratório', 'Neoplasias', 'Carcinoma in situ', None, None, None),
    ('D03', 'Melanoma in situ', 'Melanoma in situ', 'Neoplasias', 'Melanoma in situ', None, None, None),
    ('D04', 'Carcinoma in situ da pele', 'Carcinoma in situ de pele', 'Neoplasias', 'Carcinoma in situ', None, None, None),
    ('D05', 'Carcinoma in situ da mama', 'Carcinoma in situ de mama', 'Neoplasias', 'Carcinoma in situ', 'F', None, None),
    ('D06', 'Carcinoma in situ do colo do útero', 'Carcinoma in situ de colo do útero', 'Neoplasias', 'Carcinoma in situ', 'F', None, None),
    ('D07', 'Carcinoma in situ de outros órgãos genitais e dos não especificados', 'Carcinoma in situ genital', 'Neoplasias', 'Carcinoma in situ', None, None, None),
    ('D09', 'Carcinoma in situ de outras localizações e das não especificadas', 'Carcinoma in situ', 'Neoplasias', 'Carcinoma in situ', None, None, None),
    ('D10', 'Neoplasia benigna da boca e da faringe', 'Neoplasia benigna boca/faringe', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D11', 'Neoplasia benigna das glândulas salivares maiores', 'Neoplasia benigna glândula salivar', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D12', 'Neoplasia benigna do cólon, reto, canal anal e ânus', 'Neoplasia benigna intestino', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D13', 'Neoplasia benigna de outras partes e de partes mal definidas do aparelho digestivo', 'Neoplasia benigna digestivo', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D14', 'Neoplasia benigna do ouvido médio e do aparelho respiratório', 'Neoplasia benigna respiratório', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D15', 'Neoplasia benigna de outros órgãos intratorácicos e dos não especificados', 'Neoplasia benigna intratorácica', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D16', 'Neoplasia benigna do osso e cartilagem articular', 'Neoplasia benigna de osso', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D17', 'Neoplasia lipomatosa benigna', 'Lipoma', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D18', 'Hemangioma e linfangioma de qualquer localização', 'Hemangioma', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D19', 'Neoplasia benigna do tecido mesotelial', 'Neoplasia benigna mesotelial', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D20', 'Neoplasia benigna do tecido mole do retroperitônio e do peritônio', 'Neoplasia benigna retroperitônio', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D21', 'Outras neoplasias benignas do tecido conjuntivo e dos tecidos moles', 'Neoplasia benigna tecido mole', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D22', 'Nevo melanocítico', 'Nevo', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D23', 'Outras neoplasias benignas da pele', 'Neoplasia benigna de pele', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D24', 'Neoplasia benigna da mama', 'Neoplasia benigna de mama', 'Neoplasias', 'Neoplasia Benigna', 'F', None, None),
    ('D25', 'Leiomioma do útero', 'Leiomioma uterino', 'Neoplasias', 'Neoplasia Benigna', 'F', None, None),
    ('D26', 'Outras neoplasias benignas do útero', 'Neoplasia benigna de útero', 'Neoplasias', 'Neoplasia Benigna', 'F', None, None),
    ('D27', 'Neoplasia benigna do ovário', 'Neoplasia benigna de ovário', 'Neoplasias', 'Neoplasia Benigna', 'F', None, None),
    ('D28', 'Neoplasia benigna de outros órgãos genitais femininos e dos não especificados', 'Neoplasia benigna genital feminino', 'Neoplasias', 'Neoplasia Benigna', 'F', None, None),
    ('D29', 'Neoplasia benigna dos órgãos genitais masculinos', 'Neoplasia benigna genital masculino', 'Neoplasias', 'Neoplasia Benigna', 'M', None, None),
    ('D30', 'Neoplasia benigna dos órgãos urinários', 'Neoplasia benigna urinária', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D31', 'Neoplasia benigna do olho e anexos', 'Neoplasia benigna de olho', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D32', 'Neoplasia benigna das meninges', 'Neoplasia benigna de meninge', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D33', 'Neoplasia benigna do encéfalo e de outras partes do sistema nervoso central', 'Neoplasia benigna de SNC', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D34', 'Neoplasia benigna da glândula tireóide', 'Neoplasia benigna de tireóide', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D35', 'Neoplasia benigna de outras glândulas endócrinas e das não especificadas', 'Neoplasia benigna endócrina', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D36', 'Neoplasia benigna de outras localizações e de localizações não especificadas', 'Neoplasia benigna', 'Neoplasias', 'Neoplasia Benigna', None, None, None),
    ('D37', 'Neoplasia de comportamento incerto ou desconhecido da cavidade oral e dos órgãos digestivos', 'Neoplasia incerta digestivo', 'Neoplasias', 'Neoplasia Incerta', None, None, None),
    ('D38', 'Neoplasia de comportamento incerto ou desconhecido do ouvido médio e dos órgãos respiratórios e intratorácicos', 'Neoplasia incerta respiratório', 'Neoplasias', 'Neoplasia Incerta', None, None, None),
    ('D39', 'Neoplasia de comportamento incerto ou desconhecido dos órgãos genitais femininos', 'Neoplasia incerta genital feminino', 'Neoplasias', 'Neoplasia Incerta', 'F', None, None),
    ('D40', 'Neoplasia de comportamento incerto ou desconhecido dos órgãos genitais masculinos', 'Neoplasia incerta genital masculino', 'Neoplasias', 'Neoplasia Incerta', 'M', None, None),
    ('D41', 'Neoplasia de comportamento incerto ou desconhecido dos órgãos urinários', 'Neoplasia incerta urinária', 'Neoplasias', 'Neoplasia Incerta', None, None, None),
    ('D42', 'Neoplasia de comportamento incerto ou desconhecido das meninges', 'Neoplasia incerta de meninge', 'Neoplasias', 'Neoplasia Incerta', None, None, None),
    ('D43', 'Neoplasia de comportamento incerto ou desconhecido do encéfalo e do sistema nervoso central', 'Neoplasia incerta de SNC', 'Neoplasias', 'Neoplasia Incerta', None, None, None),
    ('D44', 'Neoplasia de comportamento incerto ou desconhecido das glândulas endócrinas', 'Neoplasia incerta endócrina', 'Neoplasias', 'Neoplasia Incerta', None, None, None),
    ('D45', 'Policitemia vera', 'Policitemia vera', 'Neoplasias', 'Neoplasia Hematológica', None, None, None),
    ('D46', 'Síndromes mielodisplásicas', 'Síndrome mielodisplásica', 'Neoplasias', 'Neoplasia Hematológica', None, None, None),
    ('D47', 'Outras neoplasias de comportamento incerto ou desconhecido dos tecidos linfático, hematopoético e tecidos correlatos', 'Neoplasia incerta hematológica', 'Neoplasias', 'Neoplasia Incerta', None, None, None),

    # Capítulo III - Doenças do sangue e dos órgãos hematopoéticos (D50-D89)
    ('D50', 'Anemia por deficiência de ferro', 'Anemia ferropriva', 'Doenças do Sangue', 'Anemia', None, None, None),
    ('D51', 'Anemia por deficiência de vitamina B12', 'Anemia por B12', 'Doenças do Sangue', 'Anemia', None, None, None),
    ('D52', 'Anemia por deficiência de folato', 'Anemia por folato', 'Doenças do Sangue', 'Anemia', None, None, None),
    ('D53', 'Outras anemias nutricionais', 'Anemia nutricional', 'Doenças do Sangue', 'Anemia', None, None, None),
    ('D55', 'Anemia devida a transtornos enzimáticos', 'Anemia enzimática', 'Doenças do Sangue', 'Anemia', None, None, None),
    ('D56', 'Talassemia', 'Talassemia', 'Doenças do Sangue', 'Anemia', None, None, None),
    ('D57', 'Transtornos falciformes', 'Anemia falciforme', 'Doenças do Sangue', 'Anemia', None, None, None),
    ('D58', 'Outras anemias hemolíticas hereditárias', 'Anemia hemolítica hereditária', 'Doenças do Sangue', 'Anemia', None, None, None),
    ('D59', 'Anemia hemolítica adquirida', 'Anemia hemolítica adquirida', 'Doenças do Sangue', 'Anemia', None, None, None),
    ('D60', 'Aplasia adquirida da série vermelha [eritroblastopenia]', 'Aplasia de série vermelha', 'Doenças do Sangue', 'Aplasia', None, None, None),
    ('D61', 'Outras anemias aplásticas', 'Anemia aplástica', 'Doenças do Sangue', 'Aplasia', None, None, None),
    ('D62', 'Anemia pós-hemorrágica aguda', 'Anemia pós-hemorrágica', 'Doenças do Sangue', 'Anemia', None, None, None),
    ('D63', 'Anemia em doenças crônicas classificadas em outra parte', 'Anemia em doença crônica', 'Doenças do Sangue', 'Anemia', None, None, None),
    ('D64', 'Outras anemias', 'Anemia', 'Doenças do Sangue', 'Anemia', None, None, None),
    ('D65', 'Coagulação intravascular disseminada [síndrome de desfibrinação]', 'CID', 'Doenças do Sangue', 'Coagulopatia', None, None, None),
    ('D66', 'Deficiência hereditária do fator VIII', 'Hemofilia A', 'Doenças do Sangue', 'Hemofilia', None, None, None),
    ('D67', 'Deficiência hereditária do fator IX', 'Hemofilia B', 'Doenças do Sangue', 'Hemofilia', None, None, None),
    ('D68', 'Outros defeitos da coagulação', 'Defeito de coagulação', 'Doenças do Sangue', 'Coagulopatia', None, None, None),
    ('D69', 'Púrpura e outras afecções hemorrágicas', 'Púrpura', 'Doenças do Sangue', 'Púrpura', None, None, None),
    ('D70', 'Agranulocitose', 'Agranulocitose', 'Doenças do Sangue', 'Agranulocitose', None, None, None),
    ('D71', 'Transtornos funcionais dos neutrófilos polimorfonucleares', 'Transtorno de neutrófilos', 'Doenças do Sangue', 'Transtorno de Leucócitos', None, None, None),
    ('D72', 'Outros transtornos dos glóbulos brancos', 'Transtorno de leucócitos', 'Doenças do Sangue', 'Transtorno de Leucócitos', None, None, None),
    ('D73', 'Doenças do baço', 'Doença do baço', 'Doenças do Sangue', 'Doença do Baço', None, None, None),
    ('D74', 'Metemoglobinemia', 'Metemoglobinemia', 'Doenças do Sangue', 'Metemoglobinemia', None, None, None),
    ('D75', 'Outras doenças do sangue e dos órgãos hematopoéticos', 'Doença do sangue', 'Doenças do Sangue', 'Doença do Sangue', None, None, None),
    ('D76', 'Algumas doenças que envolvem o tecido linforreticular e o sistema reticulohistiocitário', 'Doença linforreticular', 'Doenças do Sangue', 'Doença Linforreticular', None, None, None),
    ('D77', 'Outros transtornos do sangue e dos órgãos hematopoéticos em doenças classificadas em outra parte', 'Transtorno do sangue', 'Doenças do Sangue', 'Transtorno do Sangue', None, None, None),
    ('D80', 'Imunodeficiência com predomínio de defeitos de anticorpos', 'Imunodeficiência de anticorpos', 'Doenças do Sangue', 'Imunodeficiência', None, None, None),
    ('D81', 'Deficiências imunitárias combinadas', 'Imunodeficiência combinada', 'Doenças do Sangue', 'Imunodeficiência', None, None, None),
    ('D82', 'Imunodeficiência associada com outros defeitos "major"', 'Imunodeficiência associada', 'Doenças do Sangue', 'Imunodeficiência', None, None, None),
    ('D83', 'Imunodeficiência comum variável', 'Imunodeficiência comum variável', 'Doenças do Sangue', 'Imunodeficiência', None, None, None),
    ('D84', 'Outras deficiências imunitárias', 'Imunodeficiência', 'Doenças do Sangue', 'Imunodeficiência', None, None, None),
    ('D86', 'Sarcoidose', 'Sarcoidose', 'Doenças do Sangue', 'Sarcoidose', None, None, None),
    ('D89', 'Outros transtornos que comprometem o mecanismo imunitário, não classificados em outra parte', 'Transtorno imunitário', 'Doenças do Sangue', 'Transtorno Imunitário', None, None, None),
    
    # Capítulo IV - Doenças endócrinas, nutricionais e metabólicas (E00-E90)
    ('E00', 'Síndrome de deficiência congênita de iodo', 'Deficiência congênita de iodo', 'Doenças Endócrinas', 'Tireóide', None, None, None),
    ('E01', 'Transtornos da tireóide relacionados à deficiência de iodo e afecções relacionadas', 'Transtorno tireóide por deficiência de iodo', 'Doenças Endócrinas', 'Tireóide', None, None, None),
    ('E02', 'Hipotireoidismo subclínico por deficiência de iodo', 'Hipotireoidismo subclínico', 'Doenças Endócrinas', 'Tireóide', None, None, None),
    ('E03', 'Outros hipotireoidismos', 'Hipotireoidismo', 'Doenças Endócrinas', 'Tireóide', None, None, None),
    ('E04', 'Outros bócios não-tóxicos', 'Bócio não-tóxico', 'Doenças Endócrinas', 'Tireóide', None, None, None),
    ('E05', 'Tireotoxicose [hipertireoidismo]', 'Hipertireoidismo', 'Doenças Endócrinas', 'Tireóide', None, None, None),
    ('E06', 'Tireoidite', 'Tireoidite', 'Doenças Endócrinas', 'Tireóide', None, None, None),
    ('E07', 'Outros transtornos da tireóide', 'Transtorno de tireóide', 'Doenças Endócrinas', 'Tireóide', None, None, None),
    ('E10', 'Diabetes mellitus insulino-dependente', 'Diabetes tipo 1', 'Doenças Endócrinas', 'Diabetes', None, None, None),
    ('E11', 'Diabetes mellitus não-insulino-dependente', 'Diabetes tipo 2', 'Doenças Endócrinas', 'Diabetes', None, None, None),
    ('E11.0', 'Diabetes mellitus não-insulino-dependente com coma', 'Diabetes tipo 2 com coma', 'Doenças Endócrinas', 'Diabetes', None, None, None),
    ('E11.1', 'Diabetes mellitus não-insulino-dependente com cetoacidose', 'Diabetes tipo 2 com cetoacidose', 'Doenças Endócrinas', 'Diabetes', None, None, None),
    ('E11.2', 'Diabetes mellitus não-insulino-dependente com complicações renais', 'Diabetes tipo 2 com nefropatia', 'Doenças Endócrinas', 'Diabetes', None, None, None),
    ('E11.3', 'Diabetes mellitus não-insulino-dependente com complicações oculares', 'Diabetes tipo 2 com retinopatia', 'Doenças Endócrinas', 'Diabetes', None, None, None),
    ('E11.4', 'Diabetes mellitus não-insulino-dependente com complicações neurológicas', 'Diabetes tipo 2 com neuropatia', 'Doenças Endócrinas', 'Diabetes', None, None, None),
    ('E11.5', 'Diabetes mellitus não-insulino-dependente com complicações circulatórias periféricas', 'Diabetes tipo 2 com angiopatia', 'Doenças Endócrinas', 'Diabetes', None, None, None),
    ('E11.6', 'Diabetes mellitus não-insulino-dependente com outras complicações especificadas', 'Diabetes tipo 2 com outras complicações', 'Doenças Endócrinas', 'Diabetes', None, None, None),
    ('E11.7', 'Diabetes mellitus não-insulino-dependente com múltiplas complicações', 'Diabetes tipo 2 com múltiplas complicações', 'Doenças Endócrinas', 'Diabetes', None, None, None),
    ('E11.8', 'Diabetes mellitus não-insulino-dependente com complicações não especificadas', 'Diabetes tipo 2 com complicações', 'Doenças Endócrinas', 'Diabetes', None, None, None),
    ('E11.9', 'Diabetes mellitus não-insulino-dependente sem complicações', 'Diabetes tipo 2 sem complicações', 'Doenças Endócrinas', 'Diabetes', None, None, None),
    ('E12', 'Diabetes mellitus relacionado com desnutrição', 'Diabetes por desnutrição', 'Doenças Endócrinas', 'Diabetes', None, None, None),
    ('E13', 'Outros tipos especificados de diabetes mellitus', 'Diabetes especificado', 'Doenças Endócrinas', 'Diabetes', None, None, None),
    ('E14', 'Diabetes mellitus não especificado', 'Diabetes', 'Doenças Endócrinas', 'Diabetes', None, None, None),
    ('E15', 'Coma hipoglicêmico não-diabético', 'Coma hipoglicêmico', 'Doenças Endócrinas', 'Hipoglicemia', None, None, None),
    ('E16', 'Outros transtornos da secreção pancreática interna', 'Transtorno de secreção pancreática', 'Doenças Endócrinas', 'Pâncreas', None, None, None),
    ('E20', 'Hipoparatireoidismo', 'Hipoparatireoidismo', 'Doenças Endócrinas', 'Paratireóide', None, None, None),
    ('E21', 'Hiperparatireoidismo e outros transtornos da glândula paratireóide', 'Hiperparatireoidismo', 'Doenças Endócrinas', 'Paratireóide', None, None, None),
    ('E22', 'Hiperfunção da hipófise', 'Hiperfunção hipofisária', 'Doenças Endócrinas', 'Hipófise', None, None, None),
    ('E23', 'Hipofunção e outros transtornos da hipófise', 'Hipofunção hipofisária', 'Doenças Endócrinas', 'Hipófise', None, None, None),
    ('E24', 'Síndrome de Cushing', 'Síndrome de Cushing', 'Doenças Endócrinas', 'Supra-renal', None, None, None),
    ('E25', 'Transtornos adrenogenitais', 'Transtorno adrenogenital', 'Doenças Endócrinas', 'Supra-renal', None, None, None),
    ('E26', 'Hiperaldosteronismo', 'Hiperaldosteronismo', 'Doenças Endócrinas', 'Supra-renal', None, None, None),
    ('E27', 'Outros transtornos da glândula supra-renal', 'Transtorno de supra-renal', 'Doenças Endócrinas', 'Supra-renal', None, None, None),
    ('E28', 'Disfunção ovariana', 'Disfunção ovariana', 'Doenças Endócrinas', 'Ovário', 'F', None, None),
    ('E29', 'Disfunção testicular', 'Disfunção testicular', 'Doenças Endócrinas', 'Testículo', 'M', None, None),
    ('E30', 'Transtornos da puberdade não classificados em outra parte', 'Transtorno da puberdade', 'Doenças Endócrinas', 'Puberdade', None, None, None),
    ('E31', 'Disfunção poliglandular', 'Disfunção poliglandular', 'Doenças Endócrinas', 'Disfunção Poliglandular', None, None, None),
    ('E32', 'Doenças do timo', 'Doença do timo', 'Doenças Endócrinas', 'Timo', None, None, None),
    ('E34', 'Outros transtornos endócrinos', 'Transtorno endócrino', 'Doenças Endócrinas', 'Transtorno Endócrino', None, None, None),
    ('E40', 'Kwashiorkor', 'Kwashiorkor', 'Doenças Endócrinas', 'Desnutrição', None, None, None),
    ('E41', 'Marasmo nutricional', 'Marasmo', 'Doenças Endócrinas', 'Desnutrição', None, None, None),
    ('E42', 'Kwashiorkor marasmático', 'Kwashiorkor marasmático', 'Doenças Endócrinas', 'Desnutrição', None, None, None),
    ('E43', 'Desnutrição protéico-calórica grave não especificada', 'Desnutrição grave', 'Doenças Endócrinas', 'Desnutrição', None, None, None),
    ('E44', 'Desnutrição protéico-calórica de graus moderado e leve', 'Desnutrição moderada/leve', 'Doenças Endócrinas', 'Desnutrição', None, None, None),
    ('E45', 'Atraso do desenvolvimento devido à desnutrição protéico-calórica', 'Atraso por desnutrição', 'Doenças Endócrinas', 'Desnutrição', None, None, None),
    ('E46', 'Desnutrição não especificada', 'Desnutrição', 'Doenças Endócrinas', 'Desnutrição', None, None, None),
    ('E50', 'Deficiência de vitamina A', 'Deficiência de vitamina A', 'Doenças Endócrinas', 'Deficiência de Vitamina', None, None, None),
    ('E51', 'Deficiência de tiamina', 'Deficiência de tiamina', 'Doenças Endócrinas', 'Deficiência de Vitamina', None, None, None),
    ('E52', 'Deficiência de niacina [pelagra]', 'Deficiência de niacina', 'Doenças Endócrinas', 'Deficiência de Vitamina', None, None, None),
    ('E53', 'Deficiência de outras vitaminas do grupo B', 'Deficiência de vitamina B', 'Doenças Endócrinas', 'Deficiência de Vitamina', None, None, None),
    ('E54', 'Deficiência de ácido ascórbico', 'Deficiência de vitamina C', 'Doenças Endócrinas', 'Deficiência de Vitamina', None, None, None),
    ('E55', 'Deficiência de vitamina D', 'Deficiência de vitamina D', 'Doenças Endócrinas', 'Deficiência de Vitamina', None, None, None),
    ('E56', 'Outras deficiências vitamínicas', 'Deficiência vitamínica', 'Doenças Endócrinas', 'Deficiência de Vitamina', None, None, None),
    ('E58', 'Deficiência de cálcio da dieta', 'Deficiência de cálcio', 'Doenças Endócrinas', 'Deficiência Mineral', None, None, None),
    ('E59', 'Deficiência de selênio da dieta', 'Deficiência de selênio', 'Doenças Endócrinas', 'Deficiência Mineral', None, None, None),
    ('E60', 'Deficiência de zinco da dieta', 'Deficiência de zinco', 'Doenças Endócrinas', 'Deficiência Mineral', None, None, None),
    ('E61', 'Deficiência de outros elementos nutrientes', 'Deficiência de nutriente', 'Doenças Endócrinas', 'Deficiência Mineral', None, None, None),
    ('E63', 'Outras deficiências nutricionais', 'Deficiência nutricional', 'Doenças Endócrinas', 'Deficiência Nutricional', None, None, None),
    ('E64', 'Seqüelas de desnutrição e de outras deficiências nutricionais', 'Seqüela de desnutrição', 'Doenças Endócrinas', 'Seqüela Nutricional', None, None, None),
    ('E65', 'Adiposidade localizada', 'Adiposidade localizada', 'Doenças Endócrinas', 'Obesidade', None, None, None),
    ('E66', 'Obesidade', 'Obesidade', 'Doenças Endócrinas', 'Obesidade', None, None, None),
    ('E66.0', 'Obesidade devida a excesso de calorias', 'Obesidade por excesso calórico', 'Doenças Endócrinas', 'Obesidade', None, None, None),
    ('E66.01', 'Obesidade mórbida', 'Obesidade mórbida', 'Doenças Endócrinas', 'Obesidade', None, None, None),
    ('E67', 'Hiperalimentação', 'Hiperalimentação', 'Doenças Endócrinas', 'Hiperalimentação', None, None, None),
    ('E68', 'Seqüelas de hiperalimentação', 'Seqüela de hiperalimentação', 'Doenças Endócrinas', 'Seqüela Nutricional', None, None, None),
    ('E70', 'Transtornos do metabolismo de aminoácidos aromáticos', 'Transtorno de aminoácidos aromáticos', 'Doenças Endócrinas', 'Erro Inato do Metabolismo', None, None, None),
    ('E71', 'Transtornos do metabolismo de aminoácidos de cadeia ramificada e do metabolismo dos ácidos graxos', 'Transtorno de aminoácidos ramificados', 'Doenças Endócrinas', 'Erro Inato do Metabolismo', None, None, None),
    ('E72', 'Outros transtornos do metabolismo de aminoácidos', 'Transtorno de aminoácidos', 'Doenças Endócrinas', 'Erro Inato do Metabolismo', None, None, None),
    ('E73', 'Intolerância à lactose', 'Intolerância à lactose', 'Doenças Endócrinas', 'Intolerância', None, None, None),
    ('E74', 'Outros transtornos do metabolismo de carboidratos', 'Transtorno de carboidratos', 'Doenças Endócrinas', 'Erro Inato do Metabolismo', None, None, None),
    ('E75', 'Transtornos do metabolismo de esfingolipídeos e outros transtornos de depósito de lipídeos', 'Transtorno de esfingolipídeos', 'Doenças Endócrinas', 'Erro Inato do Metabolismo', None, None, None),
    ('E76', 'Transtornos do metabolismo dos glicosaminoglicanos', 'Transtorno de glicosaminoglicanos', 'Doenças Endócrinas', 'Erro Inato do Metabolismo', None, None, None),
    ('E77', 'Transtornos do metabolismo de glicoproteínas', 'Transtorno de glicoproteínas', 'Doenças Endócrinas', 'Erro Inato do Metabolismo', None, None, None),
    ('E78', 'Transtornos do metabolismo de lipoproteínas e outras lipidemias', 'Dislipidemia', 'Doenças Endócrinas', 'Dislipidemia', None, None, None),
    ('E78.0', 'Hipercolesterolemia pura', 'Hipercolesterolemia', 'Doenças Endócrinas', 'Dislipidemia', None, None, None),
    ('E78.1', 'Hipertrigliceridemia pura', 'Hipertrigliceridemia', 'Doenças Endócrinas', 'Dislipidemia', None, None, None),
    ('E78.2', 'Hiperlipidemia mista', 'Hiperlipidemia mista', 'Doenças Endócrinas', 'Dislipidemia', None, None, None),
    ('E78.4', 'Outras hiperlipidemias', 'Hiperlipidemia', 'Doenças Endócrinas', 'Dislipidemia', None, None, None),
    ('E78.5', 'Hiperlipidemia não especificada', 'Hiperlipidemia', 'Doenças Endócrinas', 'Dislipidemia', None, None, None),
    ('E79', 'Transtornos do metabolismo de purinas e pirimidinas', 'Transtorno de purinas', 'Doenças Endócrinas', 'Erro Inato do Metabolismo', None, None, None),
    ('E80', 'Transtornos do metabolismo da porfirina e da bilirrubina', 'Transtorno de porfirina', 'Doenças Endócrinas', 'Erro Inato do Metabolismo', None, None, None),
    ('E83', 'Transtornos do metabolismo de minerais', 'Transtorno de minerais', 'Doenças Endócrinas', 'Erro Inato do Metabolismo', None, None, None),
    ('E84', 'Fibrose cística', 'Fibrose cística', 'Doenças Endócrinas', 'Fibrose Cística', None, None, None),
    ('E85', 'Amiloidose', 'Amiloidose', 'Doenças Endócrinas', 'Amiloidose', None, None, None),
    ('E86', 'Depleção do volume', 'Depleção de volume', 'Doenças Endócrinas', 'Depleção', None, None, None),
    ('E87', 'Outros transtornos do equilíbrio hidroeletrolítico e ácido-básico', 'Transtorno hidroeletrolítico', 'Doenças Endócrinas', 'Transtorno Hidroeletrolítico', None, None, None),
    ('E88', 'Outros transtornos metabólicos', 'Transtorno metabólico', 'Doenças Endócrinas', 'Transtorno Metabólico', None, None, None),
    ('E89', 'Transtornos endócrinos e metabólicos pós-procedimentos, não classificados em outra parte', 'Transtorno endócrino pós-procedimento', 'Doenças Endócrinas', 'Transtorno Pós-procedimento', None, None, None),

    # Capítulo V - Transtornos mentais e comportamentais (F00-F99) - Principais
    ('F00', 'Demência na doença de Alzheimer', 'Demência de Alzheimer', 'Transtornos Mentais', 'Demência', None, None, None),
    ('F01', 'Demência vascular', 'Demência vascular', 'Transtornos Mentais', 'Demência', None, None, None),
    ('F02', 'Demência em outras doenças classificadas em outra parte', 'Demência secundária', 'Transtornos Mentais', 'Demência', None, None, None),
    ('F03', 'Demência não especificada', 'Demência', 'Transtornos Mentais', 'Demência', None, None, None),
    ('F10', 'Transtornos mentais e comportamentais devidos ao uso de álcool', 'Transtorno por álcool', 'Transtornos Mentais', 'Transtorno por Substância', None, None, None),
    ('F11', 'Transtornos mentais e comportamentais devidos ao uso de opiáceos', 'Transtorno por opiáceos', 'Transtornos Mentais', 'Transtorno por Substância', None, None, None),
    ('F12', 'Transtornos mentais e comportamentais devidos ao uso de canabinóides', 'Transtorno por canabinóides', 'Transtornos Mentais', 'Transtorno por Substância', None, None, None),
    ('F13', 'Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos', 'Transtorno por sedativos', 'Transtornos Mentais', 'Transtorno por Substância', None, None, None),
    ('F14', 'Transtornos mentais e comportamentais devidos ao uso de cocaína', 'Transtorno por cocaína', 'Transtornos Mentais', 'Transtorno por Substância', None, None, None),
    ('F15', 'Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, incluindo a cafeína', 'Transtorno por estimulantes', 'Transtornos Mentais', 'Transtorno por Substância', None, None, None),
    ('F16', 'Transtornos mentais e comportamentais devidos ao uso de alucinógenos', 'Transtorno por alucinógenos', 'Transtornos Mentais', 'Transtorno por Substância', None, None, None),
    ('F17', 'Transtornos mentais e comportamentais devidos ao uso de fumo', 'Transtorno por fumo', 'Transtornos Mentais', 'Transtorno por Substância', None, None, None),
    ('F18', 'Transtornos mentais e comportamentais devidos ao uso de solventes voláteis', 'Transtorno por solventes', 'Transtornos Mentais', 'Transtorno por Substância', None, None, None),
    ('F19', 'Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e de outras substâncias psicoativas', 'Transtorno por múltiplas drogas', 'Transtornos Mentais', 'Transtorno por Substância', None, None, None),
    ('F20', 'Esquizofrenia', 'Esquizofrenia', 'Transtornos Mentais', 'Esquizofrenia', None, None, None),
    ('F21', 'Transtorno esquizotípico', 'Transtorno esquizotípico', 'Transtornos Mentais', 'Esquizofrenia', None, None, None),
    ('F22', 'Transtornos delirantes persistentes', 'Transtorno delirante', 'Transtornos Mentais', 'Transtorno Delirante', None, None, None),
    ('F23', 'Transtornos psicóticos agudos e transitórios', 'Transtorno psicótico agudo', 'Transtornos Mentais', 'Transtorno Psicótico', None, None, None),
    ('F24', 'Transtorno delirante induzido', 'Transtorno delirante induzido', 'Transtornos Mentais', 'Transtorno Delirante', None, None, None),
    ('F25', 'Transtornos esquizoafetivos', 'Transtorno esquizoafetivo', 'Transtornos Mentais', 'Transtorno Esquizoafetivo', None, None, None),
    ('F28', 'Outros transtornos psicóticos não-orgânicos', 'Transtorno psicótico', 'Transtornos Mentais', 'Transtorno Psicótico', None, None, None),
    ('F29', 'Psicose não-orgânica não especificada', 'Psicose', 'Transtornos Mentais', 'Transtorno Psicótico', None, None, None),
    ('F30', 'Episódio maníaco', 'Episódio maníaco', 'Transtornos Mentais', 'Transtorno do Humor', None, None, None),
    ('F31', 'Transtorno afetivo bipolar', 'Transtorno bipolar', 'Transtornos Mentais', 'Transtorno do Humor', None, None, None),
    ('F32', 'Episódio depressivo', 'Episódio depressivo', 'Transtornos Mentais', 'Transtorno do Humor', None, None, None),
    ('F32.0', 'Episódio depressivo leve', 'Depressão leve', 'Transtornos Mentais', 'Transtorno do Humor', None, None, None),
    ('F32.1', 'Episódio depressivo moderado', 'Depressão moderada', 'Transtornos Mentais', 'Transtorno do Humor', None, None, None),
    ('F32.2', 'Episódio depressivo grave sem sintomas psicóticos', 'Depressão grave', 'Transtornos Mentais', 'Transtorno do Humor', None, None, None),
    ('F32.3', 'Episódio depressivo grave com sintomas psicóticos', 'Depressão grave com psicose', 'Transtornos Mentais', 'Transtorno do Humor', None, None, None),
    ('F32.8', 'Outros episódios depressivos', 'Episódio depressivo', 'Transtornos Mentais', 'Transtorno do Humor', None, None, None),
    ('F32.9', 'Episódio depressivo não especificado', 'Depressão', 'Transtornos Mentais', 'Transtorno do Humor', None, None, None),
    ('F33', 'Transtorno depressivo recorrente', 'Depressão recorrente', 'Transtornos Mentais', 'Transtorno do Humor', None, None, None),
    ('F34', 'Transtornos de humor [afetivos] persistentes', 'Transtorno de humor persistente', 'Transtornos Mentais', 'Transtorno do Humor', None, None, None),
    ('F38', 'Outros transtornos do humor [afetivos]', 'Transtorno do humor', 'Transtornos Mentais', 'Transtorno do Humor', None, None, None),
    ('F39', 'Transtorno do humor [afetivo] não especificado', 'Transtorno do humor', 'Transtornos Mentais', 'Transtorno do Humor', None, None, None),
    ('F40', 'Transtornos fóbico-ansiosos', 'Transtorno fóbico', 'Transtornos Mentais', 'Transtorno de Ansiedade', None, None, None),
    ('F41', 'Outros transtornos ansiosos', 'Transtorno de ansiedade', 'Transtornos Mentais', 'Transtorno de Ansiedade', None, None, None),
    ('F41.0', 'Transtorno de pânico [ansiedade paroxística episódica]', 'Transtorno de pânico', 'Transtornos Mentais', 'Transtorno de Ansiedade', None, None, None),
    ('F41.1', 'Ansiedade generalizada', 'Ansiedade generalizada', 'Transtornos Mentais', 'Transtorno de Ansiedade', None, None, None),
    ('F41.2', 'Transtorno misto ansioso e depressivo', 'Transtorno ansioso-depressivo', 'Transtornos Mentais', 'Transtorno de Ansiedade', None, None, None),
    ('F41.3', 'Outros transtornos ansiosos mistos', 'Transtorno ansioso', 'Transtornos Mentais', 'Transtorno de Ansiedade', None, None, None),
    ('F41.8', 'Outros transtornos ansiosos especificados', 'Transtorno de ansiedade', 'Transtornos Mentais', 'Transtorno de Ansiedade', None, None, None),
    ('F41.9', 'Transtorno ansioso não especificado', 'Transtorno de ansiedade', 'Transtornos Mentais', 'Transtorno de Ansiedade', None, None, None),
    ('F42', 'Transtorno obsessivo-compulsivo', 'TOC', 'Transtornos Mentais', 'Transtorno Obsessivo-Compulsivo', None, None, None),
    ('F43', 'Reações ao stress grave e transtornos de adaptação', 'Transtorno de adaptação', 'Transtornos Mentais', 'Transtorno de Adaptação', None, None, None),
    ('F43.0', 'Reação aguda ao stress', 'Reação aguda ao stress', 'Transtornos Mentais', 'Transtorno de Adaptação', None, None, None),
    ('F43.1', 'Transtorno de stress pós-traumático', 'TEPT', 'Transtornos Mentais', 'Transtorno de Adaptação', None, None, None),
    ('F43.2', 'Transtornos de adaptação', 'Transtorno de adaptação', 'Transtornos Mentais', 'Transtorno de Adaptação', None, None, None),
    ('F44', 'Transtornos dissociativos [de conversão]', 'Transtorno dissociativo', 'Transtornos Mentais', 'Transtorno Dissociativo', None, None, None),
    ('F45', 'Transtornos somatoformes', 'Transtorno somatoforme', 'Transtornos Mentais', 'Transtorno Somatoforme', None, None, None),
    ('F48', 'Outros transtornos neuróticos', 'Transtorno neurótico', 'Transtornos Mentais', 'Transtorno Neurótico', None, None, None),
    ('F50', 'Transtornos da alimentação', 'Transtorno alimentar', 'Transtornos Mentais', 'Transtorno Alimentar', None, None, None),
    ('F50.0', 'Anorexia nervosa', 'Anorexia nervosa', 'Transtornos Mentais', 'Transtorno Alimentar', None, None, None),
    ('F50.1', 'Anorexia nervosa atípica', 'Anorexia atípica', 'Transtornos Mentais', 'Transtorno Alimentar', None, None, None),
    ('F50.2', 'Bulimia nervosa', 'Bulimia nervosa', 'Transtornos Mentais', 'Transtorno Alimentar', None, None, None),
    ('F50.3', 'Bulimia nervosa atípica', 'Bulimia atípica', 'Transtornos Mentais', 'Transtorno Alimentar', None, None, None),
    ('F50.4', 'Hiperfagia em outras perturbações psicológicas', 'Hiperfagia', 'Transtornos Mentais', 'Transtorno Alimentar', None, None, None),
    ('F50.5', 'Vômitos associados a outras perturbações psicológicas', 'Vômito psicológico', 'Transtornos Mentais', 'Transtorno Alimentar', None, None, None),
    ('F50.8', 'Outros transtornos da alimentação', 'Transtorno alimentar', 'Transtornos Mentais', 'Transtorno Alimentar', None, None, None),
    ('F50.9', 'Transtorno da alimentação não especificado', 'Transtorno alimentar', 'Transtornos Mentais', 'Transtorno Alimentar', None, None, None),
    ('F51', 'Transtornos não-orgânicos do sono devidos a fatores emocionais', 'Transtorno do sono', 'Transtornos Mentais', 'Transtorno do Sono', None, None, None),
    ('F52', 'Disfunção sexual, não causada por transtorno ou doença orgânica', 'Disfunção sexual', 'Transtornos Mentais', 'Disfunção Sexual', None, None, None),
    ('F53', 'Transtornos mentais e comportamentais associados ao puerpério, não classificados em outra parte', 'Transtorno puerperal', 'Transtornos Mentais', 'Transtorno Puerperal', 'F', None, None),
    ('F54', 'Fatores psicológicos e comportamentais associados a doenças ou transtornos classificados em outra parte', 'Fator psicológico', 'Transtornos Mentais', 'Fator Psicológico', None, None, None),
    ('F55', 'Abuso de substâncias que não produzem dependência', 'Abuso de substância', 'Transtornos Mentais', 'Abuso de Substância', None, None, None),
    ('F59', 'Síndromes comportamentais associadas a perturbações fisiológicas e a fatores físicos não especificados', 'Síndrome comportamental', 'Transtornos Mentais', 'Síndrome Comportamental', None, None, None),
    ('F60', 'Transtornos específicos da personalidade', 'Transtorno de personalidade', 'Transtornos Mentais', 'Transtorno de Personalidade', None, None, None),
    ('F60.0', 'Personalidade paranóide', 'Personalidade paranóide', 'Transtornos Mentais', 'Transtorno de Personalidade', None, None, None),
    ('F60.1', 'Personalidade esquizóide', 'Personalidade esquizóide', 'Transtornos Mentais', 'Transtorno de Personalidade', None, None, None),
    ('F60.2', 'Personalidade dissocial', 'Personalidade dissocial', 'Transtornos Mentais', 'Transtorno de Personalidade', None, None, None),
    ('F60.3', 'Personalidade emocionalmente instável', 'Personalidade instável', 'Transtornos Mentais', 'Transtorno de Personalidade', None, None, None),
    ('F60.4', 'Personalidade histriônica', 'Personalidade histriônica', 'Transtornos Mentais', 'Transtorno de Personalidade', None, None, None),
    ('F60.5', 'Personalidade anancástica', 'Personalidade anancástica', 'Transtornos Mentais', 'Transtorno de Personalidade', None, None, None),
    ('F60.6', 'Personalidade ansiosa [esquiva]', 'Personalidade ansiosa', 'Transtornos Mentais', 'Transtorno de Personalidade', None, None, None),
    ('F60.7', 'Personalidade dependente', 'Personalidade dependente', 'Transtornos Mentais', 'Transtorno de Personalidade', None, None, None),
    ('F60.8', 'Outros transtornos específicos da personalidade', 'Transtorno de personalidade', 'Transtornos Mentais', 'Transtorno de Personalidade', None, None, None),
    ('F60.9', 'Transtorno de personalidade não especificado', 'Transtorno de personalidade', 'Transtornos Mentais', 'Transtorno de Personalidade', None, None, None),
    ('F61', 'Transtornos mistos da personalidade e outros transtornos da personalidade', 'Transtorno misto de personalidade', 'Transtornos Mentais', 'Transtorno de Personalidade', None, None, None),
    ('F62', 'Modificações duradouras da personalidade não atribuíveis a lesão ou doença cerebral', 'Modificação de personalidade', 'Transtornos Mentais', 'Modificação de Personalidade', None, None, None),
    ('F63', 'Transtornos dos hábitos e dos impulsos', 'Transtorno de impulso', 'Transtornos Mentais', 'Transtorno de Impulso', None, None, None),
    ('F64', 'Transtornos da identidade sexual', 'Transtorno de identidade sexual', 'Transtornos Mentais', 'Transtorno de Identidade Sexual', None, None, None),
    ('F65', 'Transtornos da preferência sexual', 'Transtorno de preferência sexual', 'Transtornos Mentais', 'Transtorno de Preferência Sexual', None, None, None),
    ('F66', 'Transtornos psicológicos e comportamentais associados ao desenvolvimento sexual e à sua orientação', 'Transtorno relacionado à orientação sexual', 'Transtornos Mentais', 'Transtorno Sexual', None, None, None),
    ('F68', 'Outros transtornos da personalidade e do comportamento do adulto', 'Transtorno de personalidade', 'Transtornos Mentais', 'Transtorno de Personalidade', None, None, None),
    ('F69', 'Transtorno da personalidade e do comportamento do adulto não especificado', 'Transtorno de personalidade', 'Transtornos Mentais', 'Transtorno de Personalidade', None, None, None),
    ('F70', 'Retardo mental leve', 'Retardo mental leve', 'Transtornos Mentais', 'Retardo Mental', None, None, None),
    ('F71', 'Retardo mental moderado', 'Retardo mental moderado', 'Transtornos Mentais', 'Retardo Mental', None, None, None),
    ('F72', 'Retardo mental grave', 'Retardo mental grave', 'Transtornos Mentais', 'Retardo Mental', None, None, None),
    ('F73', 'Retardo mental profundo', 'Retardo mental profundo', 'Transtornos Mentais', 'Retardo Mental', None, None, None),
    ('F78', 'Outro retardo mental', 'Retardo mental', 'Transtornos Mentais', 'Retardo Mental', None, None, None),
    ('F79', 'Retardo mental não especificado', 'Retardo mental', 'Transtornos Mentais', 'Retardo Mental', None, None, None),
    ('F80', 'Transtornos específicos do desenvolvimento da fala e da linguagem', 'Transtorno de linguagem', 'Transtornos Mentais', 'Transtorno do Desenvolvimento', None, None, None),
    ('F81', 'Transtornos específicos do desenvolvimento das habilidades escolares', 'Transtorno de aprendizagem', 'Transtornos Mentais', 'Transtorno do Desenvolvimento', None, None, None),
    ('F82', 'Transtorno específico do desenvolvimento motor', 'Transtorno motor', 'Transtornos Mentais', 'Transtorno do Desenvolvimento', None, None, None),
    ('F84', 'Transtornos globais do desenvolvimento', 'Transtorno global do desenvolvimento', 'Transtornos Mentais', 'Transtorno do Desenvolvimento', None, None, None),
    ('F84.0', 'Autismo infantil', 'Autismo', 'Transtornos Mentais', 'Transtorno do Desenvolvimento', None, None, None),
    ('F84.1', 'Autismo atípico', 'Autismo atípico', 'Transtornos Mentais', 'Transtorno do Desenvolvimento', None, None, None),
    ('F84.2', 'Síndrome de Rett', 'Síndrome de Rett', 'Transtornos Mentais', 'Transtorno do Desenvolvimento', None, None, None),
    ('F84.3', 'Outro transtorno desintegrativo da infância', 'Transtorno desintegrativo', 'Transtornos Mentais', 'Transtorno do Desenvolvimento', None, None, None),
    ('F84.4', 'Transtorno com hipercinesia associada a retardo mental e a movimentos estereotipados', 'Transtorno com hipercinesia', 'Transtornos Mentais', 'Transtorno do Desenvolvimento', None, None, None),
    ('F84.5', 'Síndrome de Asperger', 'Síndrome de Asperger', 'Transtornos Mentais', 'Transtorno do Desenvolvimento', None, None, None),
    ('F84.8', 'Outros transtornos globais do desenvolvimento', 'Transtorno global do desenvolvimento', 'Transtornos Mentais', 'Transtorno do Desenvolvimento', None, None, None),
    ('F84.9', 'Transtorno global do desenvolvimento não especificado', 'Transtorno global do desenvolvimento', 'Transtornos Mentais', 'Transtorno do Desenvolvimento', None, None, None),
    ('F88', 'Outros transtornos do desenvolvimento psicológico', 'Transtorno do desenvolvimento', 'Transtornos Mentais', 'Transtorno do Desenvolvimento', None, None, None),
    ('F89', 'Transtorno do desenvolvimento psicológico não especificado', 'Transtorno do desenvolvimento', 'Transtornos Mentais', 'Transtorno do Desenvolvimento', None, None, None),
    ('F90', 'Transtornos hipercinéticos', 'Transtorno hipercinético', 'Transtornos Mentais', 'Transtorno Hipercinético', None, None, None),
    ('F90.0', 'Perturbação da atividade e da atenção', 'TDAH', 'Transtornos Mentais', 'Transtorno Hipercinético', None, None, None),
    ('F90.1', 'Transtorno hipercinético de conduta', 'Transtorno hipercinético de conduta', 'Transtornos Mentais', 'Transtorno Hipercinético', None, None, None),
    ('F90.8', 'Outros transtornos hipercinéticos', 'Transtorno hipercinético', 'Transtornos Mentais', 'Transtorno Hipercinético', None, None, None),
    ('F90.9', 'Transtorno hipercinético não especificado', 'Transtorno hipercinético', 'Transtornos Mentais', 'Transtorno Hipercinético', None, None, None),
    ('F91', 'Transtornos de conduta', 'Transtorno de conduta', 'Transtornos Mentais', 'Transtorno de Conduta', None, None, None),
    ('F92', 'Transtornos mistos de conduta e das emoções', 'Transtorno misto de conduta', 'Transtornos Mentais', 'Transtorno de Conduta', None, None, None),
    ('F93', 'Transtornos emocionais com início especificamente na infância', 'Transtorno emocional infantil', 'Transtornos Mentais', 'Transtorno Emocional', None, None, None),
    ('F94', 'Transtornos do funcionamento social com início especificamente na infância ou na adolescência', 'Transtorno social infantil', 'Transtornos Mentais', 'Transtorno Social', None, None, None),
    ('F95', 'Transtornos de tiques', 'Transtorno de tiques', 'Transtornos Mentais', 'Transtorno de Tiques', None, None, None),
    ('F95.0', 'Tique transitório', 'Tique transitório', 'Transtornos Mentais', 'Transtorno de Tiques', None, None, None),
    ('F95.1', 'Tique motor ou vocal crônico', 'Tique crônico', 'Transtornos Mentais', 'Transtorno de Tiques', None, None, None),
    ('F95.2', 'Transtorno de tiques vocais e motores múltiplos combinados [síndrome de Gilles de la Tourette]', 'Síndrome de Tourette', 'Transtornos Mentais', 'Transtorno de Tiques', None, None, None),
    ('F95.8', 'Outros transtornos de tiques', 'Transtorno de tiques', 'Transtornos Mentais', 'Transtorno de Tiques', None, None, None),
    ('F95.9', 'Transtorno de tiques não especificado', 'Transtorno de tiques', 'Transtornos Mentais', 'Transtorno de Tiques', None, None, None),
    ('F98', 'Outros transtornos comportamentais e emocionais com início habitualmente na infância ou na adolescência', 'Transtorno comportamental infantil', 'Transtornos Mentais', 'Transtorno Comportamental', None, None, None),
    ('F98.0', 'Enurese não-orgânica', 'Enurese', 'Transtornos Mentais', 'Enurese', None, None, None),
    ('F98.1', 'Encoprese não-orgânica', 'Encoprese', 'Transtornos Mentais', 'Encoprese', None, None, None),
    ('F98.2', 'Transtorno da alimentação na infância', 'Transtorno alimentar infantil', 'Transtornos Mentais', 'Transtorno Alimentar', None, None, None),
    ('F98.3', 'Pica do lactente e do criança', 'Pica', 'Transtornos Mentais', 'Pica', None, None, None),
    ('F98.4', 'Transtorno de movimento estereotipado', 'Transtorno de movimento estereotipado', 'Transtornos Mentais', 'Transtorno de Movimento', None, None, None),
    ('F98.5', 'Gagueira [tartamudez]', 'Gagueira', 'Transtornos Mentais', 'Gagueira', None, None, None),
    ('F98.6', 'Fala precipitada', 'Fala precipitada', 'Transtornos Mentais', 'Fala Precipitada', None, None, None),
    ('F98.8', 'Outros transtornos comportamentais e emocionais especificados com início habitualmente na infância ou na adolescência', 'Transtorno comportamental infantil', 'Transtornos Mentais', 'Transtorno Comportamental', None, None, None),
    ('F98.9', 'Transtorno comportamental ou emocional não especificado com início habitualmente na infância ou na adolescência', 'Transtorno comportamental infantil', 'Transtornos Mentais', 'Transtorno Comportamental', None, None, None),
    ('F99', 'Transtorno mental não especificado', 'Transtorno mental', 'Transtornos Mentais', 'Transtorno Mental', None, None, None),
]

def gerar_sql_cid_doencas():
    """Gera SQL para inserção de códigos CID-10."""
    sql_lines = []
    
    for codigo, descricao, descricao_abreviada, categoria, subcategoria, sexo_restricao, idade_minima, idade_maxima in CID_DOENCAS:
        # Escapar aspas simples
        descricao_escaped = descricao.replace("'", "''")
        descricao_abreviada_escaped = descricao_abreviada.replace("'", "''") if descricao_abreviada else None
        categoria_escaped = categoria.replace("'", "''") if categoria else None
        subcategoria_escaped = subcategoria.replace("'", "''") if subcategoria else None
        
        # Formatar valores NULL
        sexo_restricao_sql = f"'{sexo_restricao}'" if sexo_restricao else "NULL"
        idade_minima_sql = str(idade_minima) if idade_minima is not None else "NULL"
        idade_maxima_sql = str(idade_maxima) if idade_maxima is not None else "NULL"
        descricao_abreviada_sql = f"'{descricao_abreviada_escaped}'" if descricao_abreviada else "NULL"
        categoria_sql = f"'{categoria_escaped}'" if categoria else "NULL"
        subcategoria_sql = f"'{subcategoria_escaped}'" if subcategoria else "NULL"
        
        sql = f"""-- {codigo} - {descricao}
INSERT INTO public.cid_doencas (
    id, criado_em, atualizado_em, ativo, codigo, descricao, descricao_abreviada,
    categoria, subcategoria, sexo_restricao, idade_minima, idade_maxima
)
SELECT 
    gen_random_uuid(), NOW(), NOW(), true, '{codigo}', '{descricao_escaped}', {descricao_abreviada_sql},
    {categoria_sql}, {subcategoria_sql}, {sexo_restricao_sql}, {idade_minima_sql}, {idade_maxima_sql}
WHERE NOT EXISTS (SELECT 1 FROM public.cid_doencas WHERE codigo = '{codigo}');
"""
        sql_lines.append(sql)
    
    return '\n'.join(sql_lines)

if __name__ == '__main__':
    sql = gerar_sql_cid_doencas()
    print(sql)
