
package com.upsaude.integration.cnes.wsdl.profissional;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ProfissionalSaudeServicePortType", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/profissionalsaudeservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProfissionalSaudeServicePortType {


    /**
     * Consultar os profissionais de saúde do Estabelecimento de Saude pelo código do CNES ou pelo CNPJ do CNES.
     * 
     * @param requestConsultarProfissionaisSaude
     * @return
     *     returns com.upsaude.integration.cnes.wsdl.profissional.ResponseConsultarProfissionaisSaude
     * @throws ProfissionalSaudeFault
     */
    @WebMethod
    @WebResult(name = "responseConsultarProfissionaisSaude", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/profissionalsaudeservice", partName = "responseConsultarProfissionaisSaude")
    public ResponseConsultarProfissionaisSaude consultarProfissionaisSaude(
        @WebParam(name = "requestConsultarProfissionaisSaude", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/profissionalsaudeservice", partName = "requestConsultarProfissionaisSaude")
        RequestConsultarProfissionaisSaude requestConsultarProfissionaisSaude)
        throws ProfissionalSaudeFault
    ;

    /**
     * Consultar o profissional de saúde pelo Número do CNS ou CPF.
     * 
     * @param requestConsultarProfissionalSaude
     * @return
     *     returns com.upsaude.integration.cnes.wsdl.profissional.ResponseConsultarProfissionalSaude
     * @throws ProfissionalSaudeFault
     */
    @WebMethod
    @WebResult(name = "responseConsultarProfissionalSaude", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/profissionalsaudeservice", partName = "responseConsultarProfissionalSaude")
    public ResponseConsultarProfissionalSaude consultarProfissionalSaude(
        @WebParam(name = "requestConsultarProfissionalSaude", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/profissionalsaudeservice", partName = "requestConsultarProfissionalSaude")
        RequestConsultarProfissionalSaude requestConsultarProfissionalSaude)
        throws ProfissionalSaudeFault
    ;

}
