
package com.upsaude.integration.cnes.wsdl.profissional;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ProfissionalSaudeService", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/profissionalsaudeservice", wsdlLocation = "file:/Users/wagnergrilo/Desktop/WGB/sistemas/UPSaude/code_antigravity/UPSaude-final-back/src/main/resources/assets/wsdl/cnes/v1r0/ProfissionalSaudeService_v1r0.wsdl")
public class ProfissionalSaudeService
    extends Service
{

    private static final URL PROFISSIONALSAUDESERVICE_WSDL_LOCATION;
    private static final WebServiceException PROFISSIONALSAUDESERVICE_EXCEPTION;
    private static final QName PROFISSIONALSAUDESERVICE_QNAME = new QName("http://servicos.saude.gov.br/cnes/v1r0/profissionalsaudeservice", "ProfissionalSaudeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/wagnergrilo/Desktop/WGB/sistemas/UPSaude/code_antigravity/UPSaude-final-back/src/main/resources/assets/wsdl/cnes/v1r0/ProfissionalSaudeService_v1r0.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROFISSIONALSAUDESERVICE_WSDL_LOCATION = url;
        PROFISSIONALSAUDESERVICE_EXCEPTION = e;
    }

    public ProfissionalSaudeService() {
        super(__getWsdlLocation(), PROFISSIONALSAUDESERVICE_QNAME);
    }

    public ProfissionalSaudeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROFISSIONALSAUDESERVICE_QNAME, features);
    }

    public ProfissionalSaudeService(URL wsdlLocation) {
        super(wsdlLocation, PROFISSIONALSAUDESERVICE_QNAME);
    }

    public ProfissionalSaudeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROFISSIONALSAUDESERVICE_QNAME, features);
    }

    public ProfissionalSaudeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProfissionalSaudeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProfissionalSaudeServicePortType
     */
    @WebEndpoint(name = "ProfissionalSaudeServicePort")
    public ProfissionalSaudeServicePortType getProfissionalSaudeServicePort() {
        return super.getPort(new QName("http://servicos.saude.gov.br/cnes/v1r0/profissionalsaudeservice", "ProfissionalSaudeServicePort"), ProfissionalSaudeServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProfissionalSaudeServicePortType
     */
    @WebEndpoint(name = "ProfissionalSaudeServicePort")
    public ProfissionalSaudeServicePortType getProfissionalSaudeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicos.saude.gov.br/cnes/v1r0/profissionalsaudeservice", "ProfissionalSaudeServicePort"), ProfissionalSaudeServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROFISSIONALSAUDESERVICE_EXCEPTION!= null) {
            throw PROFISSIONALSAUDESERVICE_EXCEPTION;
        }
        return PROFISSIONALSAUDESERVICE_WSDL_LOCATION;
    }

}
