
package com.upsaude.integration.cnes.wsdl.profissional;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "MSFalha", targetNamespace = "http://servicos.saude.gov.br/wsdl/mensageria/falha/v5r0/msfalha")
public class ProfissionalSaudeFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MSFalha faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ProfissionalSaudeFault(String message, MSFalha faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public ProfissionalSaudeFault(String message, MSFalha faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.upsaude.integration.cnes.wsdl.profissional.MSFalha
     */
    public MSFalha getFaultInfo() {
        return faultInfo;
    }

}
