
package com.upsaude.integration.cnes.wsdl.equipamento;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "EquipamentoServicePortType", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/equipamentoservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EquipamentoServicePortType {


    /**
     * 
     * @param requestConsultarEquipamentos
     * @return
     *     returns com.upsaude.integration.cnes.wsdl.equipamento.ResponseConsultarEquipamentos
     * @throws CnesFault
     */
    @WebMethod
    @WebResult(name = "responseConsultarEquipamentos", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/equipamentoservice", partName = "responseConsultarEquipamentos")
    public ResponseConsultarEquipamentos consultarEquipamentos(
        @WebParam(name = "requestConsultarEquipamentos", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/equipamentoservice", partName = "requestConsultarEquipamentos")
        RequestConsultarEquipamentos requestConsultarEquipamentos)
        throws CnesFault
    ;

}
