
package com.upsaude.integration.cnes.wsdl.estabelecimento.v1r0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "EstabelecimentoSaudeService", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/estabelecimentosaudeservice", wsdlLocation = "file:/Users/wagnergrilo/Desktop/WGB/sistemas/UPSaude/code_antigravity/UPSaude-final-back/src/main/resources/assets/wsdl/cnes/v1r0/EstabelecimentoSaudeService_v1r0.wsdl")
public class EstabelecimentoSaudeService
    extends Service
{

    private static final URL ESTABELECIMENTOSAUDESERVICE_WSDL_LOCATION;
    private static final WebServiceException ESTABELECIMENTOSAUDESERVICE_EXCEPTION;
    private static final QName ESTABELECIMENTOSAUDESERVICE_QNAME = new QName("http://servicos.saude.gov.br/cnes/v1r0/estabelecimentosaudeservice", "EstabelecimentoSaudeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/wagnergrilo/Desktop/WGB/sistemas/UPSaude/code_antigravity/UPSaude-final-back/src/main/resources/assets/wsdl/cnes/v1r0/EstabelecimentoSaudeService_v1r0.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ESTABELECIMENTOSAUDESERVICE_WSDL_LOCATION = url;
        ESTABELECIMENTOSAUDESERVICE_EXCEPTION = e;
    }

    public EstabelecimentoSaudeService() {
        super(__getWsdlLocation(), ESTABELECIMENTOSAUDESERVICE_QNAME);
    }

    public EstabelecimentoSaudeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESTABELECIMENTOSAUDESERVICE_QNAME, features);
    }

    public EstabelecimentoSaudeService(URL wsdlLocation) {
        super(wsdlLocation, ESTABELECIMENTOSAUDESERVICE_QNAME);
    }

    public EstabelecimentoSaudeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESTABELECIMENTOSAUDESERVICE_QNAME, features);
    }

    public EstabelecimentoSaudeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EstabelecimentoSaudeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EstabelecimentoSaudeServicePortType
     */
    @WebEndpoint(name = "EstabelecimentoSaudeServicePort")
    public EstabelecimentoSaudeServicePortType getEstabelecimentoSaudeServicePort() {
        return super.getPort(new QName("http://servicos.saude.gov.br/cnes/v1r0/estabelecimentosaudeservice", "EstabelecimentoSaudeServicePort"), EstabelecimentoSaudeServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstabelecimentoSaudeServicePortType
     */
    @WebEndpoint(name = "EstabelecimentoSaudeServicePort")
    public EstabelecimentoSaudeServicePortType getEstabelecimentoSaudeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicos.saude.gov.br/cnes/v1r0/estabelecimentosaudeservice", "EstabelecimentoSaudeServicePort"), EstabelecimentoSaudeServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ESTABELECIMENTOSAUDESERVICE_EXCEPTION!= null) {
            throw ESTABELECIMENTOSAUDESERVICE_EXCEPTION;
        }
        return ESTABELECIMENTOSAUDESERVICE_WSDL_LOCATION;
    }

}
