
package com.upsaude.integration.cnes.wsdl.cnesservice;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CnesServicePortType", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/cnesservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CnesServicePortType {


    /**
     * Consultar o Estabelecimento de Saude pelo código do CNES.
     * 
     * @param requestConsultarEstabelecimentoSaude
     * @return
     *     returns com.upsaude.integration.cnes.wsdl.cnesservice.ResponseConsultarEstabelecimentoSaude
     * @throws CnesFault
     */
    @WebMethod
    @WebResult(name = "responseConsultarEstabelecimentoSaude", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/cnesservice", partName = "responseConsultarEstabelecimentoSaude")
    public ResponseConsultarEstabelecimentoSaude consultarEstabelecimentoSaude(
        @WebParam(name = "requestConsultarEstabelecimentoSaude", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/cnesservice", partName = "requestConsultarEstabelecimentoSaude")
        RequestConsultarEstabelecimentoSaude requestConsultarEstabelecimentoSaude)
        throws CnesFault
    ;

    /**
     * Consultar o Estabelecimento de Saude pelo código IBGE do Município.
     * 
     * @param requestConsultarEstabelecimentoSaudePorMunicipio
     * @return
     *     returns com.upsaude.integration.cnes.wsdl.cnesservice.ResponseConsultarEstabelecimentoSaudePorMunicipio
     * @throws CnesFault
     */
    @WebMethod
    @WebResult(name = "responseConsultarEstabelecimentoSaudePorMunicipio", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/cnesservice", partName = "responseConsultarEstabelecimentoSaudePorMunicipio")
    public ResponseConsultarEstabelecimentoSaudePorMunicipio consultarEstabelecimentoSaudePorMunicipio(
        @WebParam(name = "requestConsultarEstabelecimentoSaudePorMunicipio", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/cnesservice", partName = "requestConsultarEstabelecimentoSaudePorMunicipio")
        RequestConsultarEstabelecimentoSaudePorMunicipio requestConsultarEstabelecimentoSaudePorMunicipio)
        throws CnesFault
    ;

    /**
     * Consultar os dados complementares do Estabelecimento de Saude.
     * 
     * @param requestConsultarDadosComplementaresEstabelecimentoSaude
     * @return
     *     returns com.upsaude.integration.cnes.wsdl.cnesservice.ResponseConsultarDadosComplementaresEstabelecimentoSaude
     * @throws CnesFault
     */
    @WebMethod
    @WebResult(name = "responseConsultarDadosComplementaresEstabelecimentoSaude", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/cnesservice", partName = "responseConsultarDadosComplementaresEstabelecimentoSaude")
    public ResponseConsultarDadosComplementaresEstabelecimentoSaude consultarDadosComplementaresEstabelecimentoSaude(
        @WebParam(name = "requestConsultarDadosComplementaresEstabelecimentoSaude", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/cnesservice", partName = "requestConsultarDadosComplementaresEstabelecimentoSaude")
        RequestConsultarDadosComplementaresEstabelecimentoSaude requestConsultarDadosComplementaresEstabelecimentoSaude)
        throws CnesFault
    ;

}
