
package com.upsaude.integration.cnes.wsdl.cnesservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CnesService", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/cnesservice", wsdlLocation = "file:/Users/wagnergrilo/Desktop/WGB/sistemas/UPSaude/code_antigravity/UPSaude-final-back/src/main/resources/assets/wsdl/cnes/v1r0/CnesService_v1r0.wsdl")
public class CnesService
    extends Service
{

    private static final URL CNESSERVICE_WSDL_LOCATION;
    private static final WebServiceException CNESSERVICE_EXCEPTION;
    private static final QName CNESSERVICE_QNAME = new QName("http://servicos.saude.gov.br/cnes/v1r0/cnesservice", "CnesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/wagnergrilo/Desktop/WGB/sistemas/UPSaude/code_antigravity/UPSaude-final-back/src/main/resources/assets/wsdl/cnes/v1r0/CnesService_v1r0.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CNESSERVICE_WSDL_LOCATION = url;
        CNESSERVICE_EXCEPTION = e;
    }

    public CnesService() {
        super(__getWsdlLocation(), CNESSERVICE_QNAME);
    }

    public CnesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CNESSERVICE_QNAME, features);
    }

    public CnesService(URL wsdlLocation) {
        super(wsdlLocation, CNESSERVICE_QNAME);
    }

    public CnesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CNESSERVICE_QNAME, features);
    }

    public CnesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CnesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CnesServicePortType
     */
    @WebEndpoint(name = "CnesServicePort")
    public CnesServicePortType getCnesServicePort() {
        return super.getPort(new QName("http://servicos.saude.gov.br/cnes/v1r0/cnesservice", "CnesServicePort"), CnesServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CnesServicePortType
     */
    @WebEndpoint(name = "CnesServicePort")
    public CnesServicePortType getCnesServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicos.saude.gov.br/cnes/v1r0/cnesservice", "CnesServicePort"), CnesServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CNESSERVICE_EXCEPTION!= null) {
            throw CNESSERVICE_EXCEPTION;
        }
        return CNESSERVICE_WSDL_LOCATION;
    }

}
